import type {
  BuildingDefinition,
  BuildingType,
  BuildingCategory,
  BuildingLevelConfig,
  ConstructionCost,
  RoomSize,
  RoomPurpose,
  FurnitureType,
  SiegeWeapon,
  SiegeWeaponType,
} from '@botworld/shared'

export const BUILDING_DEFINITIONS: Record<Exclude<BuildingType, 'custom'>, BuildingDefinition> = {
  // ===========================
  // RESIDENTIAL (1 upgrade chain)
  // ===========================
  hut: {
    type: 'hut',
    category: 'residential',
    description: 'Basic dwelling for agents, upgrades from hut to estate',
    maxLevel: 5,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        name: 'Hut',
        sizeX: 1,
        sizeY: 1,
        maxHp: 50,
        defenseRating: 5,
        upgradeCost: { wood: 5, stone: 3 },
        constructionTicks: 10,
        rooms: [{ name: 'bedroom', size: 'small', purpose: 'sleeping', defaultFurniture: ['bed'] }],
        capacity: 1,
        features: [],
      },
      {
        level: 2,
        name: 'Cottage',
        sizeX: 2,
        sizeY: 1,
        maxHp: 80,
        defenseRating: 8,
        upgradeCost: { wood: 10, stone: 5 },
        constructionTicks: 15,
        rooms: [
          { name: 'bedroom', size: 'small', purpose: 'sleeping', defaultFurniture: ['bed'] },
          { name: 'dining room', size: 'small', purpose: 'dining', defaultFurniture: ['table', 'chair'] },
        ],
        capacity: 2,
        features: [],
      },
      {
        level: 3,
        name: 'House',
        sizeX: 2,
        sizeY: 2,
        maxHp: 120,
        defenseRating: 12,
        upgradeCost: { wood: 15, stone: 10, iron: 3 },
        constructionTicks: 25,
        rooms: [
          { name: 'bedroom', size: 'medium', purpose: 'sleeping', defaultFurniture: ['bed'] },
          { name: 'dining room', size: 'medium', purpose: 'dining', defaultFurniture: ['table', 'chair'] },
          { name: 'storage', size: 'small', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        capacity: 4,
        features: ['fireplace'],
      },
      {
        level: 4,
        name: 'Manor',
        sizeX: 3,
        sizeY: 2,
        maxHp: 200,
        defenseRating: 20,
        upgradeCost: { wood: 25, stone: 20, iron: 5, gold: 5 },
        constructionTicks: 40,
        rooms: [
          { name: 'master bedroom', size: 'large', purpose: 'sleeping', defaultFurniture: ['bed'] },
          { name: 'dining hall', size: 'large', purpose: 'dining', defaultFurniture: ['table', 'chair'] },
          { name: 'storage room', size: 'medium', purpose: 'storage', defaultFurniture: ['chest'] },
          { name: 'study', size: 'small', purpose: 'study', defaultFurniture: ['table', 'chair'] },
          { name: 'lounge', size: 'small', purpose: 'entertainment', defaultFurniture: [] },
        ],
        capacity: 8,
        features: ['fireplace', 'garden'],
      },
      {
        level: 5,
        name: 'Estate',
        sizeX: 4,
        sizeY: 3,
        maxHp: 350,
        defenseRating: 35,
        upgradeCost: { wood: 40, stone: 35, iron: 10, gold: 15, crystal: 3 },
        constructionTicks: 60,
        rooms: [
          { name: 'master suite', size: 'large', purpose: 'sleeping', defaultFurniture: ['bed'] },
          { name: 'guest bedroom', size: 'large', purpose: 'sleeping', defaultFurniture: ['bed'] },
          { name: 'grand hall', size: 'large', purpose: 'dining', defaultFurniture: ['table', 'chair'] },
          { name: 'vault', size: 'medium', purpose: 'storage', defaultFurniture: ['chest', 'safe'] },
          { name: 'library', size: 'medium', purpose: 'study', defaultFurniture: ['table', 'chair', 'shelf'] },
          { name: 'sitting room', size: 'medium', purpose: 'entertainment', defaultFurniture: [] },
          { name: 'kitchen', size: 'small', purpose: 'crafting', defaultFurniture: ['oven'] },
          { name: 'entrance hall', size: 'small', purpose: 'meeting', defaultFurniture: [] },
        ],
        capacity: 12,
        features: ['fireplace', 'garden', 'balcony', 'cellar'],
      },
    ],
  },

  cottage: {
    type: 'cottage',
    category: 'residential',
    description: 'Intermediate dwelling (level 2 of hut chain)',
    maxLevel: 5,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [], // Handled by hut chain
  },

  house: {
    type: 'house',
    category: 'residential',
    description: 'Standard dwelling (level 3 of hut chain)',
    maxLevel: 5,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [], // Handled by hut chain
  },

  manor: {
    type: 'manor',
    category: 'residential',
    description: 'Large dwelling (level 4 of hut chain)',
    maxLevel: 5,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [], // Handled by hut chain
  },

  estate: {
    type: 'estate',
    category: 'residential',
    description: 'Grand dwelling (level 5 of hut chain)',
    maxLevel: 5,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [], // Handled by hut chain
  },

  // ===========================
  // PRODUCTION (8 types)
  // ===========================
  blacksmith: {
    type: 'blacksmith',
    category: 'production',
    description: 'Forge for crafting weapons, armor, and metal items',
    maxLevel: 5,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        name: 'Blacksmith',
        sizeX: 2,
        sizeY: 2,
        maxHp: 100,
        defenseRating: 15,
        upgradeCost: { stone: 20, iron: 10, wood: 10 },
        constructionTicks: 30,
        rooms: [{ name: 'forge room', size: 'medium', purpose: 'forge', defaultFurniture: ['anvil', 'forge'] }],
        features: ['basic_tools', 'basic_weapons'],
      },
      {
        level: 2,
        name: 'Improved Blacksmith',
        sizeX: 2,
        sizeY: 2,
        maxHp: 150,
        defenseRating: 20,
        upgradeCost: { stone: 15, iron: 10 },
        constructionTicks: 25,
        rooms: [
          { name: 'forge room', size: 'medium', purpose: 'forge', defaultFurniture: ['anvil', 'forge'] },
          { name: 'furnace room', size: 'small', purpose: 'crafting', defaultFurniture: [] },
        ],
        features: ['basic_tools', 'basic_weapons', 'advanced_alloys'],
      },
      {
        level: 3,
        name: 'Master Blacksmith',
        sizeX: 2,
        sizeY: 2,
        maxHp: 200,
        defenseRating: 25,
        upgradeCost: { stone: 20, iron: 15, crystal: 5 },
        constructionTicks: 35,
        rooms: [
          { name: 'forge room', size: 'medium', purpose: 'forge', defaultFurniture: ['anvil', 'forge'] },
          { name: 'furnace room', size: 'small', purpose: 'crafting', defaultFurniture: [] },
          { name: 'enchanting room', size: 'small', purpose: 'crafting', defaultFurniture: ['enchanting_table'] },
        ],
        features: ['basic_tools', 'basic_weapons', 'advanced_alloys', 'magic_enchantment'],
      },
      {
        level: 4,
        name: 'Legendary Blacksmith',
        sizeX: 2,
        sizeY: 2,
        maxHp: 250,
        defenseRating: 30,
        upgradeCost: { stone: 25, iron: 20, crystal: 10, gold: 10 },
        constructionTicks: 45,
        rooms: [
          { name: 'forge room', size: 'medium', purpose: 'forge', defaultFurniture: ['anvil', 'forge'] },
          { name: 'furnace room', size: 'small', purpose: 'crafting', defaultFurniture: [] },
          { name: 'enchanting room', size: 'small', purpose: 'crafting', defaultFurniture: ['enchanting_table'] },
        ],
        features: ['basic_tools', 'basic_weapons', 'advanced_alloys', 'magic_enchantment', 'legendary_chance_2x'],
      },
      {
        level: 5,
        name: 'Ancient Blacksmith',
        sizeX: 2,
        sizeY: 2,
        maxHp: 300,
        defenseRating: 35,
        upgradeCost: { stone: 30, iron: 25, crystal: 15, gold: 20 },
        constructionTicks: 55,
        rooms: [
          { name: 'main forge', size: 'large', purpose: 'forge', defaultFurniture: ['anvil', 'forge'] },
          { name: 'furnace', size: 'medium', purpose: 'crafting', defaultFurniture: [] },
          { name: 'enchanting chamber', size: 'small', purpose: 'crafting', defaultFurniture: ['enchanting_table'] },
        ],
        features: ['basic_tools', 'basic_weapons', 'advanced_alloys', 'magic_enchantment', 'legendary_chance_2x', 'special_material_processing'],
      },
    ],
  },

  workshop: {
    type: 'workshop',
    category: 'production',
    description: 'Crafting space for wood, leather, and cloth items',
    maxLevel: 5,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 90,
        defenseRating: 12,
        upgradeCost: { wood: 20, stone: 10 },
        constructionTicks: 25,
        rooms: [{ name: 'workshop', size: 'medium', purpose: 'crafting', defaultFurniture: ['workbench'] }],
        features: ['basic_crafting'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 2,
        maxHp: 130,
        defenseRating: 16,
        upgradeCost: { wood: 15, stone: 10, iron: 5 },
        constructionTicks: 30,
        rooms: [
          { name: 'workshop', size: 'medium', purpose: 'crafting', defaultFurniture: ['workbench'] },
          { name: 'storage', size: 'small', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['basic_crafting', 'leather_working', 'cloth_working'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 2,
        maxHp: 170,
        defenseRating: 20,
        upgradeCost: { wood: 20, stone: 15, iron: 8 },
        constructionTicks: 35,
        rooms: [
          { name: 'main workshop', size: 'large', purpose: 'crafting', defaultFurniture: ['workbench'] },
          { name: 'storage', size: 'small', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['basic_crafting', 'leather_working', 'cloth_working', 'advanced_tools'],
      },
      {
        level: 4,
        sizeX: 2,
        sizeY: 2,
        maxHp: 220,
        defenseRating: 25,
        upgradeCost: { wood: 25, stone: 20, iron: 12, gold: 8 },
        constructionTicks: 40,
        rooms: [
          { name: 'main workshop', size: 'large', purpose: 'crafting', defaultFurniture: ['workbench'] },
          { name: 'materials storage', size: 'medium', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['basic_crafting', 'leather_working', 'cloth_working', 'advanced_tools', 'quality_bonus'],
      },
      {
        level: 5,
        sizeX: 2,
        sizeY: 2,
        maxHp: 270,
        defenseRating: 30,
        upgradeCost: { wood: 30, stone: 25, iron: 15, gold: 15, crystal: 5 },
        constructionTicks: 50,
        rooms: [
          { name: 'master workshop', size: 'large', purpose: 'crafting', defaultFurniture: ['workbench'] },
          { name: 'materials vault', size: 'medium', purpose: 'storage', defaultFurniture: ['chest'] },
          { name: 'finishing room', size: 'small', purpose: 'crafting', defaultFurniture: [] },
        ],
        features: ['basic_crafting', 'leather_working', 'cloth_working', 'advanced_tools', 'quality_bonus', 'masterwork_items'],
      },
    ],
  },

  alchemy_lab: {
    type: 'alchemy_lab',
    category: 'production',
    description: 'Laboratory for brewing potions, poisons, and explosives',
    maxLevel: 5,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 80,
        defenseRating: 10,
        upgradeCost: { wood: 15, stone: 15, crystal: 5 },
        constructionTicks: 30,
        rooms: [{ name: 'lab', size: 'medium', purpose: 'alchemy', defaultFurniture: ['alchemy_table'] }],
        features: ['basic_potions'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 2,
        maxHp: 120,
        defenseRating: 14,
        upgradeCost: { wood: 10, stone: 15, crystal: 8, herb: 10 },
        constructionTicks: 35,
        rooms: [
          { name: 'lab', size: 'medium', purpose: 'alchemy', defaultFurniture: ['alchemy_table'] },
          { name: 'reagent storage', size: 'small', purpose: 'storage', defaultFurniture: ['chest', 'herb_shelf'] },
        ],
        features: ['basic_potions', 'advanced_potions', 'poisons'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 2,
        maxHp: 160,
        defenseRating: 18,
        upgradeCost: { wood: 15, stone: 20, crystal: 12, herb: 15 },
        constructionTicks: 40,
        rooms: [
          { name: 'main lab', size: 'large', purpose: 'alchemy', defaultFurniture: ['alchemy_table', 'cauldron'] },
          { name: 'reagent vault', size: 'small', purpose: 'storage', defaultFurniture: ['chest', 'herb_shelf'] },
        ],
        features: ['basic_potions', 'advanced_potions', 'poisons', 'explosives'],
      },
      {
        level: 4,
        sizeX: 2,
        sizeY: 2,
        maxHp: 210,
        defenseRating: 23,
        upgradeCost: { wood: 20, stone: 25, crystal: 18, herb: 20, gold: 10 },
        constructionTicks: 45,
        rooms: [
          { name: 'grand lab', size: 'large', purpose: 'alchemy', defaultFurniture: ['alchemy_table', 'cauldron'] },
          { name: 'reagent archive', size: 'medium', purpose: 'storage', defaultFurniture: ['chest', 'herb_shelf'] },
        ],
        features: ['basic_potions', 'advanced_potions', 'poisons', 'explosives', 'transmutation'],
      },
      {
        level: 5,
        sizeX: 2,
        sizeY: 2,
        maxHp: 260,
        defenseRating: 28,
        upgradeCost: { wood: 25, stone: 30, crystal: 25, herb: 30, gold: 20 },
        constructionTicks: 55,
        rooms: [
          { name: 'master lab', size: 'large', purpose: 'alchemy', defaultFurniture: ['alchemy_table', 'cauldron'] },
          { name: 'ancient reagents', size: 'medium', purpose: 'storage', defaultFurniture: ['chest', 'herb_shelf', 'safe'] },
          { name: 'experimentation', size: 'small', purpose: 'alchemy', defaultFurniture: [] },
        ],
        features: ['basic_potions', 'advanced_potions', 'poisons', 'explosives', 'transmutation', 'elixir_of_life'],
      },
    ],
  },

  bakery: {
    type: 'bakery',
    category: 'production',
    description: 'Produces bread, pastries, and baked goods',
    maxLevel: 3,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 1,
        maxHp: 70,
        defenseRating: 8,
        upgradeCost: { wood: 12, stone: 8 },
        constructionTicks: 20,
        rooms: [{ name: 'bakery', size: 'medium', purpose: 'crafting', defaultFurniture: ['oven'] }],
        features: ['bread_production'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 1,
        maxHp: 110,
        defenseRating: 12,
        upgradeCost: { wood: 10, stone: 10, food: 15 },
        constructionTicks: 25,
        rooms: [
          { name: 'bakery', size: 'medium', purpose: 'crafting', defaultFurniture: ['oven'] },
          { name: 'pantry', size: 'small', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['bread_production', 'pastries', 'pies'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 1,
        maxHp: 150,
        defenseRating: 16,
        upgradeCost: { wood: 15, stone: 12, food: 25, gold: 5 },
        constructionTicks: 30,
        rooms: [
          { name: 'master bakery', size: 'large', purpose: 'crafting', defaultFurniture: ['oven'] },
          { name: 'larder', size: 'medium', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['bread_production', 'pastries', 'pies', 'mass_production'],
      },
    ],
  },

  brewery: {
    type: 'brewery',
    category: 'production',
    description: 'Brews beer, wine, and spirits',
    maxLevel: 3,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 85,
        defenseRating: 10,
        upgradeCost: { wood: 15, stone: 10, food: 10 },
        constructionTicks: 25,
        rooms: [{ name: 'brewery', size: 'medium', purpose: 'crafting', defaultFurniture: ['brewing_vat'] }],
        features: ['beer_production'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 2,
        maxHp: 130,
        defenseRating: 15,
        upgradeCost: { wood: 12, stone: 15, food: 20 },
        constructionTicks: 30,
        rooms: [
          { name: 'brewery', size: 'medium', purpose: 'crafting', defaultFurniture: ['brewing_vat'] },
          { name: 'cellar', size: 'small', purpose: 'storage', defaultFurniture: [] },
        ],
        features: ['beer_production', 'wine_production'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 2,
        maxHp: 175,
        defenseRating: 20,
        upgradeCost: { wood: 18, stone: 20, food: 30, gold: 8 },
        constructionTicks: 35,
        rooms: [
          { name: 'master brewery', size: 'large', purpose: 'crafting', defaultFurniture: ['brewing_vat', 'cauldron'] },
          { name: 'aging cellar', size: 'medium', purpose: 'storage', defaultFurniture: [] },
        ],
        features: ['beer_production', 'wine_production', 'fine_spirits'],
      },
    ],
  },

  tannery: {
    type: 'tannery',
    category: 'production',
    description: 'Processes leather from animal hides',
    maxLevel: 3,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 1,
        maxHp: 75,
        defenseRating: 9,
        upgradeCost: { wood: 10, stone: 8 },
        constructionTicks: 20,
        rooms: [{ name: 'tannery', size: 'medium', purpose: 'crafting', defaultFurniture: ['tanning_rack'] }],
        features: ['leather_processing'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 1,
        maxHp: 115,
        defenseRating: 13,
        upgradeCost: { wood: 12, stone: 12 },
        constructionTicks: 25,
        rooms: [
          { name: 'tannery', size: 'medium', purpose: 'crafting', defaultFurniture: ['tanning_rack'] },
          { name: 'hide storage', size: 'small', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['leather_processing', 'quality_leather'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 1,
        maxHp: 160,
        defenseRating: 18,
        upgradeCost: { wood: 15, stone: 15, iron: 5 },
        constructionTicks: 30,
        rooms: [
          { name: 'master tannery', size: 'large', purpose: 'crafting', defaultFurniture: ['tanning_rack', 'workbench'] },
          { name: 'hide vault', size: 'medium', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['leather_processing', 'quality_leather', 'exotic_leather'],
      },
    ],
  },

  sawmill: {
    type: 'sawmill',
    category: 'production',
    description: 'Processes logs into lumber and planks',
    maxLevel: 3,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 100,
        defenseRating: 12,
        upgradeCost: { wood: 20, stone: 10, iron: 5 },
        constructionTicks: 25,
        rooms: [{ name: 'sawmill', size: 'medium', purpose: 'crafting', defaultFurniture: ['workbench'] }],
        features: ['wood_processing'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 2,
        maxHp: 150,
        defenseRating: 18,
        upgradeCost: { wood: 15, stone: 15, iron: 8 },
        constructionTicks: 30,
        rooms: [
          { name: 'sawmill', size: 'large', purpose: 'crafting', defaultFurniture: ['workbench'] },
          { name: 'lumber yard', size: 'small', purpose: 'storage', defaultFurniture: [] },
        ],
        features: ['wood_processing', 'plank_production', 'efficiency_bonus'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 2,
        maxHp: 200,
        defenseRating: 24,
        upgradeCost: { wood: 25, stone: 20, iron: 12 },
        constructionTicks: 35,
        rooms: [
          { name: 'industrial sawmill', size: 'large', purpose: 'crafting', defaultFurniture: ['workbench'] },
          { name: 'timber warehouse', size: 'medium', purpose: 'storage', defaultFurniture: [] },
        ],
        features: ['wood_processing', 'plank_production', 'efficiency_bonus', 'bulk_processing'],
      },
    ],
  },

  smelter: {
    type: 'smelter',
    category: 'production',
    description: 'Smelts ore into metal ingots and alloys',
    maxLevel: 3,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 110,
        defenseRating: 15,
        upgradeCost: { stone: 20, iron: 10, wood: 10 },
        constructionTicks: 30,
        rooms: [{ name: 'smelter', size: 'medium', purpose: 'forge', defaultFurniture: ['forge'] }],
        features: ['ore_smelting'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 2,
        maxHp: 165,
        defenseRating: 22,
        upgradeCost: { stone: 20, iron: 15, gold: 20 },
        constructionTicks: 35,
        rooms: [
          { name: 'smelting hall', size: 'large', purpose: 'forge', defaultFurniture: ['forge'] },
          { name: 'ore storage', size: 'small', purpose: 'storage', defaultFurniture: [] },
        ],
        features: ['ore_smelting', 'alloy_production'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 2,
        maxHp: 220,
        defenseRating: 28,
        upgradeCost: { stone: 25, iron: 20, gold: 30, crystal: 5 },
        constructionTicks: 40,
        rooms: [
          { name: 'industrial smelter', size: 'large', purpose: 'forge', defaultFurniture: ['forge'] },
          { name: 'metal vault', size: 'medium', purpose: 'storage', defaultFurniture: [] },
        ],
        features: ['ore_smelting', 'alloy_production', 'rare_metal_processing'],
      },
    ],
  },

  // ===========================
  // COMMERCIAL (4 types)
  // ===========================
  market_stall: {
    type: 'market_stall',
    category: 'commercial',
    description: 'Trading post that grows from stall to trade hub',
    maxLevel: 4,
    canBeOwned: true,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        name: 'Market Stall',
        sizeX: 1,
        sizeY: 1,
        maxHp: 30,
        defenseRating: 3,
        upgradeCost: { wood: 8, stone: 3 },
        constructionTicks: 10,
        rooms: [{ name: 'stall', size: 'small', purpose: 'commerce', defaultFurniture: [] }],
        features: ['item_selling'],
      },
      {
        level: 2,
        name: 'Shop',
        sizeX: 2,
        sizeY: 1,
        maxHp: 60,
        defenseRating: 6,
        upgradeCost: { wood: 12, stone: 8 },
        constructionTicks: 18,
        rooms: [
          { name: 'shop floor', size: 'medium', purpose: 'commerce', defaultFurniture: ['table'] },
          { name: 'back room', size: 'small', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['item_selling', 'indoor_shop'],
      },
      {
        level: 3,
        name: 'Emporium',
        sizeX: 3,
        sizeY: 2,
        maxHp: 120,
        defenseRating: 12,
        upgradeCost: { wood: 20, stone: 15, gold: 10 },
        constructionTicks: 30,
        rooms: [
          { name: 'showroom', size: 'large', purpose: 'commerce', defaultFurniture: ['table', 'display_case'] },
          { name: 'warehouse', size: 'medium', purpose: 'storage', defaultFurniture: ['chest'] },
          { name: 'specialty section', size: 'small', purpose: 'commerce', defaultFurniture: [] },
        ],
        features: ['item_selling', 'indoor_shop', 'multi_category'],
      },
      {
        level: 4,
        name: 'Trade Hub',
        sizeX: 4,
        sizeY: 3,
        maxHp: 200,
        defenseRating: 20,
        upgradeCost: { wood: 35, stone: 30, gold: 25 },
        constructionTicks: 50,
        rooms: [
          { name: 'grand hall', size: 'large', purpose: 'commerce', defaultFurniture: ['table', 'display_case'] },
          { name: 'goods depot', size: 'large', purpose: 'storage', defaultFurniture: ['chest'] },
          { name: 'auction floor', size: 'medium', purpose: 'commerce', defaultFurniture: ['table'] },
          { name: 'trade office', size: 'small', purpose: 'meeting', defaultFurniture: ['table', 'chair'] },
        ],
        features: ['item_selling', 'indoor_shop', 'multi_category', 'remote_trade', 'market_influence'],
      },
    ],
  },

  shop: {
    type: 'shop',
    category: 'commercial',
    description: 'Indoor shop (level 2 of market_stall chain)',
    maxLevel: 4,
    canBeOwned: true,
    requiresSettlement: true,
    levels: [], // Handled by market_stall chain
  },

  emporium: {
    type: 'emporium',
    category: 'commercial',
    description: 'Large shop (level 3 of market_stall chain)',
    maxLevel: 4,
    canBeOwned: true,
    requiresSettlement: true,
    levels: [], // Handled by market_stall chain
  },

  trade_hub: {
    type: 'trade_hub',
    category: 'commercial',
    description: 'Trading center (level 4 of market_stall chain)',
    maxLevel: 4,
    canBeOwned: true,
    requiresSettlement: true,
    levels: [], // Handled by market_stall chain
  },

  warehouse: {
    type: 'warehouse',
    category: 'commercial',
    description: 'Large storage facility for goods',
    maxLevel: 3,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 120,
        defenseRating: 15,
        upgradeCost: { wood: 25, stone: 15 },
        constructionTicks: 25,
        rooms: [{ name: 'storage hall', size: 'large', purpose: 'storage', defaultFurniture: ['chest'] }],
        capacity: 100,
        features: ['bulk_storage'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 2,
        maxHp: 180,
        defenseRating: 22,
        upgradeCost: { wood: 20, stone: 20 },
        constructionTicks: 30,
        rooms: [
          { name: 'main warehouse', size: 'large', purpose: 'storage', defaultFurniture: ['chest'] },
          { name: 'overflow storage', size: 'large', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        capacity: 200,
        features: ['bulk_storage'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 2,
        maxHp: 250,
        defenseRating: 30,
        upgradeCost: { wood: 30, stone: 30, iron: 10 },
        constructionTicks: 40,
        rooms: [
          { name: 'grand warehouse', size: 'large', purpose: 'storage', defaultFurniture: ['chest'] },
          { name: 'secure vault', size: 'large', purpose: 'storage', defaultFurniture: ['chest', 'safe'] },
          { name: 'loading dock', size: 'medium', purpose: 'storage', defaultFurniture: [] },
        ],
        capacity: 500,
        features: ['bulk_storage', 'secure_storage'],
      },
    ],
  },

  bank: {
    type: 'bank',
    category: 'commercial',
    description: 'Secure storage for gold with financial services',
    maxLevel: 3,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 150,
        defenseRating: 25,
        upgradeCost: { stone: 30, iron: 15, gold: 10 },
        constructionTicks: 35,
        rooms: [
          { name: 'banking hall', size: 'medium', purpose: 'commerce', defaultFurniture: ['table'] },
          { name: 'vault', size: 'small', purpose: 'storage', defaultFurniture: ['safe'] },
        ],
        features: ['gold_storage'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 2,
        maxHp: 220,
        defenseRating: 35,
        upgradeCost: { stone: 25, iron: 20, gold: 20 },
        constructionTicks: 40,
        rooms: [
          { name: 'main hall', size: 'large', purpose: 'commerce', defaultFurniture: ['table'] },
          { name: 'secure vault', size: 'medium', purpose: 'storage', defaultFurniture: ['safe'] },
        ],
        features: ['gold_storage', 'loans'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 2,
        maxHp: 300,
        defenseRating: 45,
        upgradeCost: { stone: 35, iron: 25, gold: 35 },
        constructionTicks: 50,
        rooms: [
          { name: 'grand hall', size: 'large', purpose: 'commerce', defaultFurniture: ['table'] },
          { name: 'treasury', size: 'large', purpose: 'storage', defaultFurniture: ['safe'] },
          { name: 'private office', size: 'small', purpose: 'meeting', defaultFurniture: ['table', 'chair'] },
        ],
        features: ['gold_storage', 'loans', 'investments'],
      },
    ],
  },

  // ===========================
  // MILITARY (7 types)
  // ===========================
  watchtower: {
    type: 'watchtower',
    category: 'military',
    description: 'Defensive tower for surveillance and defense',
    maxLevel: 3,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 1,
        sizeY: 1,
        maxHp: 100,
        defenseRating: 20,
        upgradeCost: { wood: 15, stone: 20 },
        constructionTicks: 25,
        rooms: [{ name: 'lookout', size: 'small', purpose: 'meeting', defaultFurniture: [] }],
        features: ['vision_range'],
      },
      {
        level: 2,
        sizeX: 1,
        sizeY: 1,
        maxHp: 150,
        defenseRating: 30,
        upgradeCost: { wood: 10, stone: 25 },
        constructionTicks: 30,
        rooms: [{ name: 'observation deck', size: 'medium', purpose: 'meeting', defaultFurniture: [] }],
        features: ['vision_range', 'alarm_system'],
      },
      {
        level: 3,
        sizeX: 1,
        sizeY: 1,
        maxHp: 210,
        defenseRating: 40,
        upgradeCost: { wood: 12, stone: 30, iron: 10 },
        constructionTicks: 35,
        rooms: [
          { name: 'guard post', size: 'medium', purpose: 'meeting', defaultFurniture: ['weapon_rack'] },
          { name: 'quarters', size: 'small', purpose: 'sleeping', defaultFurniture: ['bed'] },
        ],
        features: ['vision_range', 'alarm_system', 'arrow_defense'],
      },
    ],
  },

  barracks: {
    type: 'barracks',
    category: 'military',
    description: 'Military housing and training facility',
    maxLevel: 3,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 3,
        sizeY: 2,
        maxHp: 180,
        defenseRating: 25,
        upgradeCost: { wood: 30, stone: 25, iron: 10 },
        constructionTicks: 35,
        rooms: [
          { name: 'barracks', size: 'large', purpose: 'sleeping', defaultFurniture: ['bed'] },
          { name: 'armory', size: 'small', purpose: 'storage', defaultFurniture: ['chest', 'weapon_rack'] },
        ],
        capacity: 10,
        features: ['troop_training'],
      },
      {
        level: 2,
        sizeX: 3,
        sizeY: 2,
        maxHp: 260,
        defenseRating: 35,
        upgradeCost: { wood: 25, stone: 35, iron: 15 },
        constructionTicks: 40,
        rooms: [
          { name: 'dormitory', size: 'large', purpose: 'sleeping', defaultFurniture: ['bed'] },
          { name: 'training yard', size: 'medium', purpose: 'training', defaultFurniture: ['training_dummy'] },
          { name: 'equipment room', size: 'small', purpose: 'storage', defaultFurniture: ['chest', 'weapon_rack'] },
        ],
        capacity: 20,
        features: ['troop_training', 'advanced_training'],
      },
      {
        level: 3,
        sizeX: 3,
        sizeY: 2,
        maxHp: 350,
        defenseRating: 45,
        upgradeCost: { wood: 30, stone: 50, iron: 25, gold: 15 },
        constructionTicks: 50,
        rooms: [
          { name: 'elite quarters', size: 'large', purpose: 'sleeping', defaultFurniture: ['bed'] },
          { name: 'combat hall', size: 'large', purpose: 'training', defaultFurniture: ['training_dummy', 'weapon_rack'] },
          { name: 'arsenal', size: 'medium', purpose: 'storage', defaultFurniture: ['chest', 'weapon_rack'] },
        ],
        capacity: 30,
        features: ['troop_training', 'advanced_training', 'elite_training'],
      },
    ],
  },

  wall_section: {
    type: 'wall_section',
    category: 'military',
    description: 'Defensive wall segment',
    maxLevel: 3,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 1,
        sizeY: 1,
        maxHp: 300,
        defenseRating: 50,
        upgradeCost: { stone: 25, wood: 10 },
        constructionTicks: 20,
        rooms: [],
        features: [],
      },
      {
        level: 2,
        sizeX: 1,
        sizeY: 1,
        maxHp: 500,
        defenseRating: 80,
        upgradeCost: { stone: 30, iron: 10 },
        constructionTicks: 25,
        rooms: [],
        features: ['reinforced'],
      },
      {
        level: 3,
        sizeX: 1,
        sizeY: 1,
        maxHp: 800,
        defenseRating: 120,
        upgradeCost: { stone: 40, iron: 20 },
        constructionTicks: 30,
        rooms: [],
        features: ['reinforced', 'battlements'],
      },
    ],
  },

  gate: {
    type: 'gate',
    category: 'military',
    description: 'Fortified entry point in walls',
    maxLevel: 3,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 1,
        maxHp: 200,
        defenseRating: 35,
        upgradeCost: { wood: 20, stone: 15, iron: 10 },
        constructionTicks: 25,
        rooms: [],
        features: ['lockable'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 1,
        maxHp: 350,
        defenseRating: 60,
        upgradeCost: { wood: 15, stone: 25, iron: 20 },
        constructionTicks: 30,
        rooms: [],
        features: ['lockable', 'reinforced'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 1,
        maxHp: 500,
        defenseRating: 90,
        upgradeCost: { wood: 20, stone: 35, iron: 30 },
        constructionTicks: 40,
        rooms: [],
        features: ['lockable', 'reinforced', 'guard_post'],
      },
    ],
  },

  siege_workshop: {
    type: 'siege_workshop',
    category: 'military',
    description: 'Workshop for crafting siege weapons',
    maxLevel: 2,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 3,
        sizeY: 2,
        maxHp: 150,
        defenseRating: 18,
        upgradeCost: { wood: 35, stone: 20, iron: 15 },
        constructionTicks: 40,
        rooms: [{ name: 'workshop', size: 'large', purpose: 'crafting', defaultFurniture: ['workbench'] }],
        features: ['siege_weapon_crafting'],
      },
      {
        level: 2,
        sizeX: 3,
        sizeY: 2,
        maxHp: 230,
        defenseRating: 28,
        upgradeCost: { wood: 30, stone: 30, iron: 25 },
        constructionTicks: 50,
        rooms: [
          { name: 'main workshop', size: 'large', purpose: 'crafting', defaultFurniture: ['workbench', 'anvil'] },
          { name: 'parts storage', size: 'medium', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['siege_weapon_crafting', 'advanced_siege_weapons'],
      },
    ],
  },

  armory: {
    type: 'armory',
    category: 'military',
    description: 'Storage for weapons and armor',
    maxLevel: 3,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 140,
        defenseRating: 28,
        upgradeCost: { stone: 25, iron: 15 },
        constructionTicks: 30,
        rooms: [{ name: 'armory', size: 'large', purpose: 'storage', defaultFurniture: ['chest', 'weapon_rack'] }],
        capacity: 50,
        features: ['weapon_storage'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 2,
        maxHp: 210,
        defenseRating: 40,
        upgradeCost: { stone: 30, iron: 25 },
        constructionTicks: 35,
        rooms: [
          { name: 'main armory', size: 'large', purpose: 'storage', defaultFurniture: ['chest', 'weapon_rack'] },
          { name: 'secondary storage', size: 'medium', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        capacity: 100,
        features: ['weapon_storage', 'armor_storage'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 2,
        maxHp: 290,
        defenseRating: 55,
        upgradeCost: { stone: 40, iron: 35 },
        constructionTicks: 45,
        rooms: [
          { name: 'grand armory', size: 'large', purpose: 'storage', defaultFurniture: ['chest', 'weapon_rack'] },
          { name: 'secure vault', size: 'large', purpose: 'storage', defaultFurniture: ['safe', 'weapon_rack'] },
        ],
        capacity: 200,
        features: ['weapon_storage', 'armor_storage', 'equipment_maintenance'],
      },
    ],
  },

  prison: {
    type: 'prison',
    category: 'military',
    description: 'Facility for holding prisoners',
    maxLevel: 2,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 200,
        defenseRating: 40,
        upgradeCost: { stone: 30, iron: 20 },
        constructionTicks: 35,
        rooms: [
          { name: 'cell block', size: 'small', purpose: 'prison', defaultFurniture: ['jail_cell'] },
          { name: 'holding area', size: 'small', purpose: 'prison', defaultFurniture: ['jail_cell'] },
        ],
        capacity: 5,
        features: ['prisoner_holding'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 2,
        maxHp: 320,
        defenseRating: 65,
        upgradeCost: { stone: 40, iron: 35 },
        constructionTicks: 45,
        rooms: [
          { name: 'secure cells', size: 'medium', purpose: 'prison', defaultFurniture: ['jail_cell'] },
          { name: 'isolation cells', size: 'small', purpose: 'prison', defaultFurniture: ['jail_cell'] },
          { name: 'guard station', size: 'small', purpose: 'meeting', defaultFurniture: ['table'] },
        ],
        capacity: 10,
        features: ['prisoner_holding', 'interrogation'],
      },
    ],
  },

  // ===========================
  // SOCIAL (8 types)
  // ===========================
  tavern: {
    type: 'tavern',
    category: 'social',
    description: 'Social gathering place with food, drink, and lodging',
    maxLevel: 5,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 3,
        sizeY: 3,
        maxHp: 120,
        defenseRating: 14,
        upgradeCost: { wood: 30, stone: 20 },
        constructionTicks: 35,
        rooms: [
          { name: 'common room', size: 'large', purpose: 'dining', defaultFurniture: ['table', 'chair'] },
          { name: 'kitchen', size: 'small', purpose: 'crafting', defaultFurniture: ['oven'] },
        ],
        capacity: 15,
        features: ['social_hub', 'food_service', 'drink_service'],
      },
      {
        level: 2,
        sizeX: 3,
        sizeY: 3,
        maxHp: 180,
        defenseRating: 20,
        upgradeCost: { wood: 25, stone: 25, gold: 5 },
        constructionTicks: 40,
        rooms: [
          { name: 'taproom', size: 'large', purpose: 'dining', defaultFurniture: ['table', 'chair'] },
          { name: 'kitchen', size: 'medium', purpose: 'crafting', defaultFurniture: ['oven', 'cauldron'] },
          { name: 'guest room', size: 'small', purpose: 'sleeping', defaultFurniture: ['bed'] },
        ],
        capacity: 20,
        features: ['social_hub', 'food_service', 'drink_service', 'lodging'],
      },
      {
        level: 3,
        sizeX: 3,
        sizeY: 3,
        maxHp: 240,
        defenseRating: 26,
        upgradeCost: { wood: 30, stone: 30, gold: 10 },
        constructionTicks: 45,
        rooms: [
          { name: 'great hall', size: 'large', purpose: 'dining', defaultFurniture: ['table', 'chair', 'fireplace'] },
          { name: 'kitchen', size: 'medium', purpose: 'crafting', defaultFurniture: ['oven', 'cauldron'] },
          { name: 'lodging', size: 'medium', purpose: 'sleeping', defaultFurniture: ['bed'] },
          { name: 'stage', size: 'small', purpose: 'entertainment', defaultFurniture: [] },
        ],
        capacity: 25,
        features: ['social_hub', 'food_service', 'drink_service', 'lodging', 'entertainment'],
      },
      {
        level: 4,
        sizeX: 3,
        sizeY: 3,
        maxHp: 310,
        defenseRating: 33,
        upgradeCost: { wood: 35, stone: 35, gold: 20 },
        constructionTicks: 50,
        rooms: [
          { name: 'grand hall', size: 'large', purpose: 'dining', defaultFurniture: ['table', 'chair', 'fireplace'] },
          { name: 'gourmet kitchen', size: 'large', purpose: 'crafting', defaultFurniture: ['oven', 'cauldron'] },
          { name: 'rooms', size: 'medium', purpose: 'sleeping', defaultFurniture: ['bed'] },
          { name: 'performance hall', size: 'medium', purpose: 'entertainment', defaultFurniture: [] },
          { name: 'private lounge', size: 'small', purpose: 'meeting', defaultFurniture: ['table', 'chair'] },
        ],
        capacity: 30,
        features: ['social_hub', 'food_service', 'drink_service', 'lodging', 'entertainment', 'vip_area'],
      },
      {
        level: 5,
        sizeX: 3,
        sizeY: 3,
        maxHp: 390,
        defenseRating: 40,
        upgradeCost: { wood: 40, stone: 45, gold: 35 },
        constructionTicks: 60,
        rooms: [
          { name: 'legendary hall', size: 'large', purpose: 'dining', defaultFurniture: ['table', 'chair', 'fireplace', 'throne'] },
          { name: 'master kitchen', size: 'large', purpose: 'crafting', defaultFurniture: ['oven', 'cauldron'] },
          { name: 'luxury suites', size: 'large', purpose: 'sleeping', defaultFurniture: ['bed'] },
          { name: 'theater', size: 'large', purpose: 'entertainment', defaultFurniture: [] },
          { name: 'vip lounge', size: 'medium', purpose: 'meeting', defaultFurniture: ['table', 'chair'] },
          { name: 'game room', size: 'small', purpose: 'entertainment', defaultFurniture: [] },
        ],
        capacity: 40,
        features: ['social_hub', 'food_service', 'drink_service', 'lodging', 'entertainment', 'vip_area', 'gambling'],
      },
    ],
  },

  library: {
    type: 'library',
    category: 'social',
    description: 'Repository of knowledge for research and study',
    maxLevel: 5,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 3,
        sizeY: 3,
        maxHp: 100,
        defenseRating: 12,
        upgradeCost: { wood: 25, stone: 20 },
        constructionTicks: 30,
        rooms: [{ name: 'reading room', size: 'large', purpose: 'study', defaultFurniture: ['shelf', 'table', 'chair'] }],
        features: ['research', 'knowledge_storage'],
      },
      {
        level: 2,
        sizeX: 3,
        sizeY: 3,
        maxHp: 150,
        defenseRating: 18,
        upgradeCost: { wood: 20, stone: 25, gold: 5 },
        constructionTicks: 35,
        rooms: [
          { name: 'main library', size: 'large', purpose: 'study', defaultFurniture: ['shelf', 'table', 'chair'] },
          { name: 'study nook', size: 'medium', purpose: 'study', defaultFurniture: ['shelf'] },
        ],
        features: ['research', 'knowledge_storage', 'advanced_research'],
      },
      {
        level: 3,
        sizeX: 3,
        sizeY: 3,
        maxHp: 200,
        defenseRating: 24,
        upgradeCost: { wood: 25, stone: 30, gold: 10 },
        constructionTicks: 40,
        rooms: [
          { name: 'grand hall', size: 'large', purpose: 'study', defaultFurniture: ['shelf', 'table', 'chair'] },
          { name: 'archives', size: 'large', purpose: 'study', defaultFurniture: ['shelf'] },
          { name: 'rare books', size: 'small', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['research', 'knowledge_storage', 'advanced_research', 'rare_books'],
      },
      {
        level: 4,
        sizeX: 3,
        sizeY: 3,
        maxHp: 260,
        defenseRating: 31,
        upgradeCost: { wood: 30, stone: 35, gold: 20 },
        constructionTicks: 50,
        rooms: [
          { name: 'great library', size: 'large', purpose: 'study', defaultFurniture: ['shelf', 'table', 'chair', 'lectern'] },
          { name: 'historical archives', size: 'large', purpose: 'study', defaultFurniture: ['shelf'] },
          { name: 'research wing', size: 'medium', purpose: 'study', defaultFurniture: ['shelf', 'table'] },
          { name: 'restricted section', size: 'small', purpose: 'storage', defaultFurniture: ['safe'] },
        ],
        features: ['research', 'knowledge_storage', 'advanced_research', 'rare_books', 'research_bonus'],
      },
      {
        level: 5,
        sizeX: 3,
        sizeY: 3,
        maxHp: 330,
        defenseRating: 38,
        upgradeCost: { wood: 35, stone: 45, gold: 35, crystal: 10 },
        constructionTicks: 60,
        rooms: [
          { name: 'ancient library', size: 'large', purpose: 'study', defaultFurniture: ['shelf', 'table', 'chair', 'lectern'] },
          { name: 'tome vault', size: 'large', purpose: 'study', defaultFurniture: ['shelf', 'display_case'] },
          { name: 'scholar chambers', size: 'large', purpose: 'study', defaultFurniture: ['shelf', 'table'] },
          { name: 'secret archive', size: 'medium', purpose: 'storage', defaultFurniture: ['safe'] },
          { name: 'meditation room', size: 'small', purpose: 'study', defaultFurniture: [] },
        ],
        features: ['research', 'knowledge_storage', 'advanced_research', 'rare_books', 'research_bonus', 'forbidden_knowledge'],
      },
    ],
  },

  temple: {
    type: 'temple',
    category: 'social',
    description: 'Place of worship with healing and blessing services',
    maxLevel: 3,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 3,
        sizeY: 3,
        maxHp: 160,
        defenseRating: 20,
        upgradeCost: { stone: 40, wood: 20, gold: 10 },
        constructionTicks: 40,
        rooms: [
          { name: 'sanctuary', size: 'large', purpose: 'worship', defaultFurniture: ['altar'] },
          { name: 'clergy room', size: 'small', purpose: 'meeting', defaultFurniture: [] },
        ],
        features: ['healing', 'blessing'],
      },
      {
        level: 2,
        sizeX: 3,
        sizeY: 3,
        maxHp: 240,
        defenseRating: 30,
        upgradeCost: { stone: 40, wood: 20, gold: 20, crystal: 5 },
        constructionTicks: 50,
        rooms: [
          { name: 'grand sanctum', size: 'large', purpose: 'worship', defaultFurniture: ['altar', 'lectern'] },
          { name: 'healing chamber', size: 'medium', purpose: 'medical', defaultFurniture: ['bed'] },
          { name: 'clergy quarters', size: 'small', purpose: 'meeting', defaultFurniture: [] },
        ],
        features: ['healing', 'blessing', 'resurrection'],
      },
      {
        level: 3,
        sizeX: 3,
        sizeY: 3,
        maxHp: 330,
        defenseRating: 42,
        upgradeCost: { stone: 50, wood: 25, gold: 35, crystal: 15 },
        constructionTicks: 60,
        rooms: [
          { name: 'divine hall', size: 'large', purpose: 'worship', defaultFurniture: ['altar', 'lectern', 'throne'] },
          { name: 'miracle ward', size: 'large', purpose: 'medical', defaultFurniture: ['bed'] },
          { name: 'high priest chamber', size: 'medium', purpose: 'meeting', defaultFurniture: ['table'] },
          { name: 'offering vault', size: 'small', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['healing', 'blessing', 'resurrection', 'divine_intervention'],
      },
    ],
  },

  guild_hall: {
    type: 'guild_hall',
    category: 'social',
    description: 'Headquarters for guild operations and management',
    maxLevel: 3,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 3,
        sizeY: 3,
        maxHp: 180,
        defenseRating: 22,
        upgradeCost: { wood: 35, stone: 30, gold: 15 },
        constructionTicks: 40,
        rooms: [
          { name: 'meeting hall', size: 'large', purpose: 'meeting', defaultFurniture: ['table', 'chair'] },
          { name: 'guild office', size: 'small', purpose: 'meeting', defaultFurniture: ['table'] },
        ],
        capacity: 20,
        features: ['guild_management'],
      },
      {
        level: 2,
        sizeX: 3,
        sizeY: 3,
        maxHp: 270,
        defenseRating: 33,
        upgradeCost: { wood: 30, stone: 40, gold: 25 },
        constructionTicks: 50,
        rooms: [
          { name: 'grand hall', size: 'large', purpose: 'meeting', defaultFurniture: ['table', 'chair', 'throne'] },
          { name: 'administration', size: 'medium', purpose: 'meeting', defaultFurniture: ['table'] },
          { name: 'guild vault', size: 'small', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        capacity: 35,
        features: ['guild_management', 'quest_board'],
      },
      {
        level: 3,
        sizeX: 3,
        sizeY: 3,
        maxHp: 370,
        defenseRating: 45,
        upgradeCost: { wood: 40, stone: 55, gold: 40 },
        constructionTicks: 60,
        rooms: [
          { name: 'council chamber', size: 'large', purpose: 'meeting', defaultFurniture: ['table', 'chair', 'throne'] },
          { name: 'operations center', size: 'large', purpose: 'meeting', defaultFurniture: ['table'] },
          { name: 'treasury', size: 'medium', purpose: 'storage', defaultFurniture: ['safe'] },
          { name: 'training hall', size: 'small', purpose: 'training', defaultFurniture: ['training_dummy'] },
        ],
        capacity: 50,
        features: ['guild_management', 'quest_board', 'guild_bank', 'training_facility'],
      },
    ],
  },

  arena: {
    type: 'arena',
    category: 'social',
    description: 'Combat arena for tournaments and competitions',
    maxLevel: 3,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 4,
        sizeY: 4,
        maxHp: 250,
        defenseRating: 30,
        upgradeCost: { stone: 50, wood: 30, iron: 15 },
        constructionTicks: 50,
        rooms: [
          { name: 'arena floor', size: 'large', purpose: 'training', defaultFurniture: [] },
          { name: 'arena office', size: 'small', purpose: 'meeting', defaultFurniture: ['table'] },
        ],
        features: ['combat_tournaments'],
      },
      {
        level: 2,
        sizeX: 4,
        sizeY: 4,
        maxHp: 370,
        defenseRating: 45,
        upgradeCost: { stone: 50, wood: 25, iron: 25, gold: 15 },
        constructionTicks: 60,
        rooms: [
          { name: 'grand arena', size: 'large', purpose: 'training', defaultFurniture: ['weapon_rack'] },
          { name: 'management', size: 'medium', purpose: 'meeting', defaultFurniture: ['table'] },
          { name: 'equipment room', size: 'small', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        features: ['combat_tournaments', 'spectator_seating', 'betting'],
      },
      {
        level: 3,
        sizeX: 4,
        sizeY: 4,
        maxHp: 510,
        defenseRating: 62,
        upgradeCost: { stone: 60, wood: 30, iron: 35, gold: 30 },
        constructionTicks: 75,
        rooms: [
          { name: 'colosseum', size: 'large', purpose: 'training', defaultFurniture: ['weapon_rack', 'training_dummy'] },
          { name: 'champion office', size: 'large', purpose: 'meeting', defaultFurniture: ['table', 'throne'] },
          { name: 'armory', size: 'medium', purpose: 'storage', defaultFurniture: ['chest', 'weapon_rack'] },
          { name: 'waiting room', size: 'small', purpose: 'entertainment', defaultFurniture: [] },
        ],
        features: ['combat_tournaments', 'spectator_seating', 'betting', 'grand_championships'],
      },
    ],
  },

  academy: {
    type: 'academy',
    category: 'social',
    description: 'Educational institution for skill training',
    maxLevel: 3,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 3,
        sizeY: 3,
        maxHp: 140,
        defenseRating: 16,
        upgradeCost: { wood: 30, stone: 25, gold: 10 },
        constructionTicks: 35,
        rooms: [
          { name: 'classroom', size: 'large', purpose: 'training', defaultFurniture: ['table', 'chair'] },
          { name: 'office', size: 'small', purpose: 'meeting', defaultFurniture: ['table'] },
        ],
        features: ['skill_training'],
      },
      {
        level: 2,
        sizeX: 3,
        sizeY: 3,
        maxHp: 210,
        defenseRating: 24,
        upgradeCost: { wood: 25, stone: 35, gold: 20 },
        constructionTicks: 45,
        rooms: [
          { name: 'lecture hall', size: 'large', purpose: 'training', defaultFurniture: ['table', 'chair', 'lectern'] },
          { name: 'practice room', size: 'medium', purpose: 'training', defaultFurniture: [] },
          { name: 'faculty office', size: 'small', purpose: 'meeting', defaultFurniture: ['table'] },
        ],
        features: ['skill_training', 'advanced_training'],
      },
      {
        level: 3,
        sizeX: 3,
        sizeY: 3,
        maxHp: 290,
        defenseRating: 33,
        upgradeCost: { wood: 30, stone: 45, gold: 35, crystal: 10 },
        constructionTicks: 55,
        rooms: [
          { name: 'grand hall', size: 'large', purpose: 'training', defaultFurniture: ['table', 'chair', 'lectern'] },
          { name: 'advanced lab', size: 'large', purpose: 'training', defaultFurniture: ['workbench'] },
          { name: 'research library', size: 'medium', purpose: 'study', defaultFurniture: ['shelf'] },
          { name: 'dean office', size: 'small', purpose: 'meeting', defaultFurniture: ['table'] },
        ],
        features: ['skill_training', 'advanced_training', 'master_training'],
      },
    ],
  },

  hospital: {
    type: 'hospital',
    category: 'social',
    description: 'Medical facility for healing and treatment',
    maxLevel: 3,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 120,
        defenseRating: 15,
        upgradeCost: { wood: 25, stone: 20, herb: 15 },
        constructionTicks: 30,
        rooms: [
          { name: 'ward', size: 'medium', purpose: 'medical', defaultFurniture: ['bed'] },
          { name: 'supply room', size: 'small', purpose: 'storage', defaultFurniture: ['chest'] },
        ],
        capacity: 5,
        features: ['healing'],
      },
      {
        level: 2,
        sizeX: 2,
        sizeY: 2,
        maxHp: 180,
        defenseRating: 22,
        upgradeCost: { wood: 20, stone: 30, herb: 25, gold: 10 },
        constructionTicks: 40,
        rooms: [
          { name: 'main ward', size: 'large', purpose: 'medical', defaultFurniture: ['bed'] },
          { name: 'medicine storage', size: 'small', purpose: 'storage', defaultFurniture: ['chest', 'herb_shelf'] },
          { name: 'physician office', size: 'small', purpose: 'meeting', defaultFurniture: ['table'] },
        ],
        capacity: 10,
        features: ['healing', 'surgery'],
      },
      {
        level: 3,
        sizeX: 2,
        sizeY: 2,
        maxHp: 250,
        defenseRating: 30,
        upgradeCost: { wood: 25, stone: 40, herb: 40, gold: 20, crystal: 5 },
        constructionTicks: 50,
        rooms: [
          { name: 'grand ward', size: 'large', purpose: 'medical', defaultFurniture: ['bed'] },
          { name: 'intensive care', size: 'medium', purpose: 'medical', defaultFurniture: ['bed'] },
          { name: 'apothecary', size: 'small', purpose: 'storage', defaultFurniture: ['chest', 'herb_shelf', 'alchemy_table'] },
        ],
        capacity: 15,
        features: ['healing', 'surgery', 'advanced_healing'],
      },
    ],
  },

  courthouse: {
    type: 'courthouse',
    category: 'social',
    description: 'Legal center for trials and law enforcement',
    maxLevel: 2,
    canBeOwned: false,
    requiresSettlement: true,
    levels: [
      {
        level: 1,
        sizeX: 3,
        sizeY: 2,
        maxHp: 180,
        defenseRating: 25,
        upgradeCost: { stone: 35, wood: 25, gold: 15 },
        constructionTicks: 40,
        rooms: [
          { name: 'courtroom', size: 'large', purpose: 'meeting', defaultFurniture: ['table', 'chair', 'throne'] },
          { name: 'judge chambers', size: 'small', purpose: 'meeting', defaultFurniture: ['table'] },
        ],
        features: ['trials', 'law_enforcement'],
      },
      {
        level: 2,
        sizeX: 3,
        sizeY: 2,
        maxHp: 270,
        defenseRating: 38,
        upgradeCost: { stone: 40, wood: 30, gold: 30 },
        constructionTicks: 50,
        rooms: [
          { name: 'grand court', size: 'large', purpose: 'meeting', defaultFurniture: ['table', 'chair', 'throne', 'lectern'] },
          { name: 'judicial office', size: 'medium', purpose: 'meeting', defaultFurniture: ['table'] },
          { name: 'records room', size: 'small', purpose: 'storage', defaultFurniture: ['chest', 'shelf'] },
        ],
        features: ['trials', 'law_enforcement', 'public_records'],
      },
    ],
  },

  // ===========================
  // INFRASTRUCTURE (7 types)
  // ===========================
  bridge: {
    type: 'bridge',
    category: 'infrastructure',
    description: 'Allows crossing of water',
    maxLevel: 1,
    canBeOwned: false,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 1,
        sizeY: 1,
        maxHp: 100,
        defenseRating: 10,
        upgradeCost: { wood: 10, stone: 5 },
        constructionTicks: 15,
        rooms: [],
        features: ['water_crossing'],
      },
    ],
  },

  well: {
    type: 'well',
    category: 'infrastructure',
    description: 'Provides water and farming bonus',
    maxLevel: 1,
    canBeOwned: false,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 1,
        sizeY: 1,
        maxHp: 50,
        defenseRating: 5,
        upgradeCost: { stone: 10, wood: 5 },
        constructionTicks: 15,
        rooms: [],
        features: ['water_source', 'farming_bonus'],
      },
    ],
  },

  road_lamp: {
    type: 'road_lamp',
    category: 'infrastructure',
    description: 'Illuminates area at night',
    maxLevel: 1,
    canBeOwned: false,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 1,
        sizeY: 1,
        maxHp: 20,
        defenseRating: 2,
        upgradeCost: { wood: 5, iron: 2 },
        constructionTicks: 5,
        rooms: [],
        features: ['night_vision'],
      },
    ],
  },

  signpost: {
    type: 'signpost',
    category: 'infrastructure',
    description: 'Provides directional information',
    maxLevel: 1,
    canBeOwned: false,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 1,
        sizeY: 1,
        maxHp: 10,
        defenseRating: 1,
        upgradeCost: { wood: 3 },
        constructionTicks: 3,
        rooms: [],
        features: ['direction'],
      },
    ],
  },

  dock: {
    type: 'dock',
    category: 'infrastructure',
    description: 'Water access for fishing and trade',
    maxLevel: 1,
    canBeOwned: false,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 4,
        sizeY: 2,
        maxHp: 150,
        defenseRating: 12,
        upgradeCost: { wood: 40, stone: 20 },
        constructionTicks: 35,
        rooms: [{ name: 'dock storage', size: 'medium', purpose: 'storage', defaultFurniture: ['chest'] }],
        features: ['fishing', 'water_trade'],
      },
    ],
  },

  stable: {
    type: 'stable',
    category: 'infrastructure',
    description: 'Housing for mounts and animals',
    maxLevel: 1,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 80,
        defenseRating: 10,
        upgradeCost: { wood: 20, stone: 10 },
        constructionTicks: 20,
        rooms: [{ name: 'stalls', size: 'large', purpose: 'storage', defaultFurniture: [] }],
        capacity: 10,
        features: ['mount_storage', 'speed_bonus'],
      },
    ],
  },

  cemetery: {
    type: 'cemetery',
    category: 'infrastructure',
    description: 'Final resting place for the deceased',
    maxLevel: 1,
    canBeOwned: false,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 100,
        defenseRating: 8,
        upgradeCost: { stone: 20, wood: 10 },
        constructionTicks: 25,
        rooms: [],
        features: ['death_records', 'mourning'],
      },
    ],
  },

  // ===========================
  // SPECIAL (4 types)
  // ===========================
  portal_shrine: {
    type: 'portal_shrine',
    category: 'special',
    description: 'Magical portal for teleportation',
    maxLevel: 1,
    canBeOwned: false,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 200,
        defenseRating: 25,
        upgradeCost: { stone: 40, crystal: 30, gold: 25 },
        constructionTicks: 60,
        rooms: [{ name: 'portal chamber', size: 'medium', purpose: 'worship', defaultFurniture: ['altar'] }],
        features: ['teleportation'],
      },
    ],
  },

  ancient_forge: {
    type: 'ancient_forge',
    category: 'special',
    description: 'Legendary forge for ultimate crafting',
    maxLevel: 1,
    canBeOwned: false,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 3,
        sizeY: 3,
        maxHp: 300,
        defenseRating: 35,
        upgradeCost: { stone: 50, iron: 40, crystal: 40, gold: 50 },
        constructionTicks: 80,
        rooms: [
          { name: 'ancient forge', size: 'large', purpose: 'forge', defaultFurniture: ['anvil', 'forge', 'enchanting_table'] },
          { name: 'artifact vault', size: 'small', purpose: 'storage', defaultFurniture: ['safe'] },
        ],
        features: ['legendary_crafting_only'],
      },
    ],
  },

  dragon_lair: {
    type: 'dragon_lair',
    category: 'special',
    description: 'Ancient dragon dwelling with treasure',
    maxLevel: 1,
    canBeOwned: false,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 4,
        sizeY: 4,
        maxHp: 500,
        defenseRating: 60,
        upgradeCost: { stone: 80, crystal: 50, gold: 100 },
        constructionTicks: 100,
        rooms: [
          { name: 'hoard chamber', size: 'large', purpose: 'storage', defaultFurniture: ['chest', 'safe', 'display_case'] },
          { name: 'dragon nest', size: 'large', purpose: 'sleeping', defaultFurniture: [] },
        ],
        features: ['treasure_hoard', 'dragon_guardian'],
      },
    ],
  },

  wizard_tower: {
    type: 'wizard_tower',
    category: 'special',
    description: 'Tower of magic research and scroll crafting',
    maxLevel: 1,
    canBeOwned: true,
    requiresSettlement: false,
    levels: [
      {
        level: 1,
        sizeX: 2,
        sizeY: 2,
        maxHp: 150,
        defenseRating: 20,
        upgradeCost: { stone: 30, wood: 20, crystal: 25, gold: 20 },
        constructionTicks: 50,
        rooms: [
          { name: 'study', size: 'medium', purpose: 'study', defaultFurniture: ['table', 'shelf', 'enchanting_table'] },
          { name: 'lab', size: 'small', purpose: 'alchemy', defaultFurniture: ['alchemy_table'] },
        ],
        features: ['scroll_crafting', 'magic_research'],
      },
    ],
  },
}

export const SIEGE_WEAPONS: Record<SiegeWeaponType, SiegeWeapon> = {
  catapult: {
    type: 'catapult',
    damage: 50,
    targetPreference: ['wall_section', 'watchtower', 'gate'],
    craftCost: { wood: 30, iron: 15, stone: 10 },
    craftTicks: 30,
  },
  battering_ram: {
    type: 'battering_ram',
    damage: 80,
    targetPreference: ['gate'],
    craftCost: { wood: 40, iron: 20 },
    craftTicks: 25,
  },
  siege_ladder: {
    type: 'siege_ladder',
    damage: 0,
    targetPreference: ['wall_section'],
    craftCost: { wood: 15 },
    craftTicks: 10,
  },
  fire_arrows: {
    type: 'fire_arrows',
    damage: 30,
    targetPreference: ['hut', 'cottage', 'house', 'tavern', 'bakery'],
    craftCost: { wood: 5, iron: 3 },
    craftTicks: 5,
  },
}

export function getBuildingDefinition(type: BuildingType): BuildingDefinition | undefined {
  if (type === 'custom') return undefined
  return BUILDING_DEFINITIONS[type]
}

export function getConstructionCost(type: BuildingType, level: number): ConstructionCost | undefined {
  const def = getBuildingDefinition(type)
  if (!def) return undefined
  const lvl = def.levels.find((l) => l.level === level)
  return lvl?.upgradeCost
}

export function getConstructionTime(type: BuildingType, level: number, workerCount: number): number {
  const def = getBuildingDefinition(type)
  if (!def) return 100
  const lvl = def.levels.find((l) => l.level === level)
  if (!lvl) return 100
  // More workers = faster, with diminishing returns
  const speedMultiplier = 1 + Math.log2(Math.max(1, workerCount)) * 0.5
  return Math.max(5, Math.ceil(lvl.constructionTicks / speedMultiplier))
}
