import Phaser from 'phaser'

/**
 * Boot scene: loads all PNG assets generated by Gemini,
 * then transitions to WorldScene.
 */
export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: 'BootScene' })
  }

  preload(): void {
    // Tile sprites (12 types)
    const tileTypes = ['grass', 'water', 'deep_water', 'forest', 'dense_forest', 'sand', 'mountain', 'road', 'building', 'farmland', 'snow', 'swamp']
    for (const type of tileTypes) {
      this.load.image(`tile_${type}`, `assets/tiles/tile_${type}.png`)
    }

    // Agent sprites (5 characters)
    for (let i = 0; i < 5; i++) {
      this.load.image(`agent_${i}`, `assets/agents/agent_${i}.png`)
    }

    // Resource icons (6 types)
    const resourceTypes = ['wood', 'stone', 'food', 'iron', 'gold', 'herb']
    for (const type of resourceTypes) {
      this.load.image(`resource_${type}`, `assets/resources/resource_${type}.png`)
    }

    // Action icons (5 types)
    const actionTypes = ['gather', 'talk', 'craft', 'rest', 'trade']
    for (const type of actionTypes) {
      this.load.image(`action_${type}`, `assets/actions/action_${type}.png`)
    }

    // Fallback: generate resource_indicator procedurally in create()
  }

  create(): void {
    // Generate fallback textures for anything that uses generic keys
    this.generateFallbackTextures()

    this.scene.start('WorldScene')
  }

  private generateFallbackTextures(): void {
    // Generic resource indicator (sparkle) - used as fallback
    const g = this.add.graphics()
    g.fillStyle(0xf1c40f, 0.9)
    g.beginPath()
    g.moveTo(4, 0)
    g.lineTo(7, 4)
    g.lineTo(4, 8)
    g.lineTo(1, 4)
    g.closePath()
    g.fillPath()
    g.generateTexture('resource_indicator', 8, 8)
    g.destroy()

    // Procedural fallback tiles for new biome types (simple colored diamonds)
    const fallbackTiles: Record<string, number> = {
      tile_deep_water: 0x0a2a5e,
      tile_dense_forest: 0x1a4a2a,
      tile_snow: 0xe8e8f0,
      tile_swamp: 0x4a5a3a,
    }
    for (const [key, color] of Object.entries(fallbackTiles)) {
      if (!this.textures.exists(key)) {
        const fg = this.add.graphics()
        fg.fillStyle(color, 1)
        fg.beginPath()
        fg.moveTo(64, 0)
        fg.lineTo(128, 32)
        fg.lineTo(64, 64)
        fg.lineTo(0, 32)
        fg.closePath()
        fg.fillPath()
        fg.generateTexture(key, 128, 64)
        fg.destroy()
      }
    }

    // agent_default fallback (reuses agent_0)
    if (this.textures.exists('agent_0') && !this.textures.exists('agent_default')) {
      const source = this.textures.get('agent_0').getSourceImage()
      this.textures.addImage('agent_default', source as HTMLImageElement)
    }

    // Shadow texture (procedural - tiny ellipse)
    const sg = this.add.graphics()
    sg.fillStyle(0x000000, 0.15)
    sg.fillEllipse(12, 4, 20, 7)
    sg.generateTexture('agent_shadow', 24, 8)
    sg.destroy()

    // Selection ring texture
    const rg = this.add.graphics()
    rg.lineStyle(1.5, 0xf0d060, 0.8)
    rg.strokeEllipse(12, 4, 22, 9)
    rg.generateTexture('selection_ring', 24, 8)
    rg.destroy()
  }
}
