/**
 * Creature template definitions and spawn tables for Botworld
 *
 * Contains:
 * - 15 animal templates (passive, neutral, tameable wildlife)
 * - 25 monster templates (aggressive enemies and bosses)
 * - Biome spawn tables with weighted random spawning
 * - Den/dungeon templates for boss encounters
 */

import type {
  CreatureTier,
  CreatureType,
  CreatureBehavior,
  ActiveTime,
  LootEntry,
  BiomeSpawnTable,
  DenType,
} from '@botworld/shared'

// ============================================================================
// INTERFACES
// ============================================================================

export interface CreatureTemplate {
  id: string // e.g. 'rabbit', 'goblin', 'dragon'
  name: string // display name
  tier: CreatureTier
  creatureType: CreatureType
  behavior: CreatureBehavior
  baseHp: number
  baseAttack: number
  baseDefense: number
  speed: number // tiles per tick (1=normal, 2=fast, 0.5=slow)
  stats: { strength: number; agility: number; intelligence: number; perception: number }
  loot: LootEntry[]
  habitat: string[] // biome types
  activeTime: ActiveTime | 'any' // 'any' for templates, converted to 'both' at runtime
  aggroRadius: number
  respawnTicks: number
  isAnimal: boolean
  canBeTamed?: boolean
  produces?: { item: string; interval: number }
  abilities?: string[]
  weaknesses?: string[]
  immunities?: string[]
  packType?: string // if this creature forms packs
  denType?: DenType // if this creature lives in dens
  description: string
}

export interface DenTemplate {
  denType: DenType
  name: string
  tier: CreatureTier
  creatureTemplates: { templateId: string; count: [number, number] }[] // [min, max]
  bossTemplateId: string
  floors: number
  roomsPerFloor: [number, number] // [min, max]
  respawnTicks: number
  description: string
}

// ============================================================================
// ANIMAL TEMPLATES (15 total)
// ============================================================================

const ANIMAL_TEMPLATES: CreatureTemplate[] = [
  // --- TIER 1: PASSIVE ANIMALS ---
  {
    id: 'rabbit',
    name: 'Rabbit',
    tier: 1,
    creatureType: 'animal',
    behavior: 'passive',
    baseHp: 5,
    baseAttack: 1,
    baseDefense: 0,
    speed: 2,
    stats: { strength: 1, agility: 8, intelligence: 2, perception: 6 },
    loot: [
      { itemType: 'meat', chance: 0.8, quantityMin: 1, quantityMax: 1 },
      { itemType: 'hide', chance: 0.5, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['grass', 'meadow', 'forest'],
    activeTime: 'any',
    aggroRadius: 0,
    respawnTicks: 200,
    isAnimal: true,
    description: 'Quick and harmless, these rabbits flee at the first sign of danger',
  },
  {
    id: 'chicken',
    name: 'Chicken',
    tier: 1,
    creatureType: 'animal',
    behavior: 'passive',
    baseHp: 3,
    baseAttack: 1,
    baseDefense: 0,
    speed: 1,
    stats: { strength: 1, agility: 4, intelligence: 1, perception: 3 },
    loot: [
      { itemType: 'meat', chance: 0.9, quantityMin: 1, quantityMax: 1 },
      { itemType: 'feather', chance: 0.7, quantityMin: 2, quantityMax: 2 },
    ],
    habitat: ['farmland'],
    activeTime: 'day',
    aggroRadius: 0,
    respawnTicks: 300,
    isAnimal: true,
    produces: { item: 'egg', interval: 20 },
    description: 'Common farm bird that produces eggs regularly',
  },
  {
    id: 'cow',
    name: 'Cow',
    tier: 1,
    creatureType: 'animal',
    behavior: 'passive',
    baseHp: 20,
    baseAttack: 2,
    baseDefense: 1,
    speed: 0.5,
    stats: { strength: 6, agility: 2, intelligence: 2, perception: 3 },
    loot: [
      { itemType: 'meat', chance: 0.9, quantityMin: 3, quantityMax: 3 },
      { itemType: 'hide', chance: 0.8, quantityMin: 2, quantityMax: 2 },
    ],
    habitat: ['farmland', 'meadow'],
    activeTime: 'any',
    aggroRadius: 0,
    respawnTicks: 400,
    isAnimal: true,
    produces: { item: 'milk', interval: 30 },
    description: 'Gentle grazing animal that provides milk and meat',
  },
  {
    id: 'sheep',
    name: 'Sheep',
    tier: 1,
    creatureType: 'animal',
    behavior: 'passive',
    baseHp: 15,
    baseAttack: 1,
    baseDefense: 0,
    speed: 1,
    stats: { strength: 3, agility: 3, intelligence: 2, perception: 4 },
    loot: [
      { itemType: 'meat', chance: 0.9, quantityMin: 2, quantityMax: 2 },
      { itemType: 'wool', chance: 0.8, quantityMin: 3, quantityMax: 3 },
    ],
    habitat: ['farmland', 'meadow'],
    activeTime: 'any',
    aggroRadius: 0,
    respawnTicks: 400,
    isAnimal: true,
    produces: { item: 'wool', interval: 40 },
    description: 'Woolly farm animal that can be sheared regularly',
  },
  {
    id: 'fish',
    name: 'Fish',
    tier: 1,
    creatureType: 'animal',
    behavior: 'passive',
    baseHp: 2,
    baseAttack: 0,
    baseDefense: 0,
    speed: 1,
    stats: { strength: 1, agility: 6, intelligence: 1, perception: 4 },
    loot: [{ itemType: 'raw_fish', chance: 1.0, quantityMin: 1, quantityMax: 1 }],
    habitat: ['water', 'river', 'ocean'],
    activeTime: 'any',
    aggroRadius: 0,
    respawnTicks: 150,
    isAnimal: true,
    description: 'Common fish found in water sources',
  },
  {
    id: 'butterfly',
    name: 'Butterfly',
    tier: 1,
    creatureType: 'animal',
    behavior: 'passive',
    baseHp: 1,
    baseAttack: 0,
    baseDefense: 0,
    speed: 2,
    stats: { strength: 1, agility: 10, intelligence: 1, perception: 5 },
    loot: [{ itemType: 'butterfly_wing', chance: 0.5, quantityMin: 1, quantityMax: 1 }],
    habitat: ['grass', 'meadow', 'forest'],
    activeTime: 'day',
    aggroRadius: 0,
    respawnTicks: 180,
    isAnimal: true,
    description: 'Beautiful flying insect with delicate wings',
  },

  // --- TIER 2: NEUTRAL ANIMALS ---
  {
    id: 'deer',
    name: 'Deer',
    tier: 2,
    creatureType: 'animal',
    behavior: 'neutral',
    baseHp: 15,
    baseAttack: 4,
    baseDefense: 2,
    speed: 2,
    stats: { strength: 4, agility: 8, intelligence: 3, perception: 7 },
    loot: [
      { itemType: 'meat', chance: 0.9, quantityMin: 2, quantityMax: 2 },
      { itemType: 'hide', chance: 0.8, quantityMin: 2, quantityMax: 2 },
      { itemType: 'antler', chance: 0.1, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['forest', 'meadow', 'grass'],
    activeTime: 'any',
    aggroRadius: 3,
    respawnTicks: 350,
    isAnimal: true,
    description: 'Graceful forest dweller, flees when threatened but will defend if cornered',
  },
  {
    id: 'boar',
    name: 'Boar',
    tier: 2,
    creatureType: 'animal',
    behavior: 'territorial',
    baseHp: 25,
    baseAttack: 8,
    baseDefense: 3,
    speed: 1.5,
    stats: { strength: 7, agility: 5, intelligence: 3, perception: 6 },
    loot: [
      { itemType: 'meat', chance: 0.9, quantityMin: 3, quantityMax: 3 },
      { itemType: 'hide', chance: 0.7, quantityMin: 2, quantityMax: 2 },
      { itemType: 'tusk', chance: 0.2, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['forest', 'dense_forest', 'swamp'],
    activeTime: 'any',
    aggroRadius: 4,
    respawnTicks: 400,
    isAnimal: true,
    description: 'Aggressive wild pig that charges when provoked',
  },
  {
    id: 'bear',
    name: 'Bear',
    tier: 2,
    creatureType: 'animal',
    behavior: 'territorial',
    baseHp: 60,
    baseAttack: 12,
    baseDefense: 5,
    speed: 1,
    stats: { strength: 12, agility: 5, intelligence: 4, perception: 6 },
    loot: [
      { itemType: 'meat', chance: 0.9, quantityMin: 5, quantityMax: 5 },
      { itemType: 'hide', chance: 0.8, quantityMin: 3, quantityMax: 3 },
      { itemType: 'claw', chance: 0.3, quantityMin: 2, quantityMax: 2 },
    ],
    habitat: ['forest', 'mountain'],
    activeTime: 'any',
    aggroRadius: 5,
    respawnTicks: 600,
    isAnimal: true,
    description: 'Powerful predator that defends its territory fiercely',
  },
  {
    id: 'eagle',
    name: 'Eagle',
    tier: 2,
    creatureType: 'animal',
    behavior: 'neutral',
    baseHp: 20,
    baseAttack: 7,
    baseDefense: 2,
    speed: 3,
    stats: { strength: 5, agility: 10, intelligence: 4, perception: 10 },
    loot: [{ itemType: 'feather', chance: 0.7, quantityMin: 5, quantityMax: 5 }],
    habitat: ['mountain', 'cliff'],
    activeTime: 'day',
    aggroRadius: 4,
    respawnTicks: 500,
    isAnimal: true,
    abilities: ['flying'],
    description: 'Majestic bird of prey that soars above mountain peaks',
  },
  {
    id: 'horse',
    name: 'Horse',
    tier: 2,
    creatureType: 'animal',
    behavior: 'neutral',
    baseHp: 30,
    baseAttack: 5,
    baseDefense: 3,
    speed: 3,
    stats: { strength: 8, agility: 9, intelligence: 4, perception: 6 },
    loot: [
      { itemType: 'hide', chance: 0.7, quantityMin: 2, quantityMax: 2 },
      { itemType: 'meat', chance: 0.6, quantityMin: 3, quantityMax: 3 },
    ],
    habitat: ['grass', 'meadow'],
    activeTime: 'any',
    aggroRadius: 3,
    respawnTicks: 700,
    isAnimal: true,
    canBeTamed: true,
    description: 'Swift and intelligent, can be tamed for riding',
  },
  {
    id: 'wolf',
    name: 'Wolf',
    tier: 2,
    creatureType: 'animal',
    behavior: 'predator',
    baseHp: 35,
    baseAttack: 9,
    baseDefense: 3,
    speed: 2,
    stats: { strength: 7, agility: 8, intelligence: 5, perception: 8 },
    loot: [
      { itemType: 'hide', chance: 0.6, quantityMin: 1, quantityMax: 1 },
      { itemType: 'fang', chance: 0.3, quantityMin: 1, quantityMax: 1 },
      { itemType: 'raw_meat', chance: 0.7, quantityMin: 2, quantityMax: 2 },
    ],
    habitat: ['forest', 'dense_forest', 'mountain', 'snow'],
    activeTime: 'any',
    aggroRadius: 6,
    respawnTicks: 500,
    isAnimal: true,
    packType: 'wolf_pack',
    description: 'Pack hunter that coordinates with its allies',
  },

  // --- TIER 3: SPECIAL ANIMALS ---
  {
    id: 'giant_spider',
    name: 'Giant Spider',
    tier: 3,
    creatureType: 'animal',
    behavior: 'aggressive',
    baseHp: 40,
    baseAttack: 10,
    baseDefense: 4,
    speed: 1.5,
    stats: { strength: 6, agility: 7, intelligence: 3, perception: 9 },
    loot: [
      { itemType: 'spider_silk', chance: 0.6, quantityMin: 2, quantityMax: 2 },
      { itemType: 'venom', chance: 0.3, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['cave', 'dense_forest'],
    activeTime: 'any',
    aggroRadius: 5,
    respawnTicks: 500,
    isAnimal: true,
    abilities: ['web_trap', 'poison'],
    description: 'Enormous arachnid that traps prey in sticky webs',
  },
  {
    id: 'dire_wolf',
    name: 'Dire Wolf',
    tier: 3,
    creatureType: 'animal',
    behavior: 'predator',
    baseHp: 70,
    baseAttack: 14,
    baseDefense: 6,
    speed: 2,
    stats: { strength: 10, agility: 9, intelligence: 6, perception: 9 },
    loot: [
      { itemType: 'dire_hide', chance: 0.5, quantityMin: 1, quantityMax: 1 },
      { itemType: 'fang', chance: 0.4, quantityMin: 2, quantityMax: 2 },
    ],
    habitat: ['snow', 'mountain'],
    activeTime: 'any',
    aggroRadius: 7,
    respawnTicks: 800,
    isAnimal: true,
    packType: 'wolf_pack',
    description: 'Ancient breed of massive wolf, alpha of its pack',
  },
  {
    id: 'griffin',
    name: 'Griffin',
    tier: 3,
    creatureType: 'animal',
    behavior: 'territorial',
    baseHp: 120,
    baseAttack: 18,
    baseDefense: 10,
    speed: 3,
    stats: { strength: 12, agility: 10, intelligence: 7, perception: 10 },
    loot: [{ itemType: 'griffin_feather', chance: 0.4, quantityMin: 3, quantityMax: 3 }],
    habitat: ['mountain'],
    activeTime: 'any',
    aggroRadius: 8,
    respawnTicks: 1200,
    isAnimal: true,
    canBeTamed: true,
    abilities: ['flying'],
    description: 'Legendary creature with lion body and eagle head, can be tamed by the worthy',
  },
]

// ============================================================================
// MONSTER TEMPLATES (25 total)
// ============================================================================

const MONSTER_TEMPLATES: CreatureTemplate[] = [
  // --- TIER 1: BEGINNER MONSTERS ---
  {
    id: 'slime',
    name: 'Slime',
    tier: 1,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 30,
    baseAttack: 4,
    baseDefense: 1,
    speed: 0.5,
    stats: { strength: 3, agility: 2, intelligence: 1, perception: 3 },
    loot: [{ itemType: 'slime_gel', chance: 0.6, quantityMin: 1, quantityMax: 2 }],
    habitat: ['grass', 'forest', 'cave', 'swamp'],
    activeTime: 'any',
    aggroRadius: 4,
    respawnTicks: 250,
    isAnimal: false,
    abilities: ['split_on_low_hp'],
    description: 'Gelatinous blob that splits when near death',
  },
  {
    id: 'rat',
    name: 'Giant Rat',
    tier: 1,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 10,
    baseAttack: 3,
    baseDefense: 1,
    speed: 2,
    stats: { strength: 2, agility: 7, intelligence: 2, perception: 6 },
    loot: [{ itemType: 'rat_tail', chance: 0.5, quantityMin: 1, quantityMax: 1 }],
    habitat: ['cave', 'ruins'],
    activeTime: 'any',
    aggroRadius: 5,
    respawnTicks: 200,
    isAnimal: false,
    packType: 'rat_swarm',
    description: 'Disease-carrying rodent that attacks in swarms',
  },
  {
    id: 'bat',
    name: 'Cave Bat',
    tier: 1,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 8,
    baseAttack: 4,
    baseDefense: 1,
    speed: 2,
    stats: { strength: 2, agility: 8, intelligence: 2, perception: 9 },
    loot: [{ itemType: 'bat_wing', chance: 0.5, quantityMin: 1, quantityMax: 1 }],
    habitat: ['cave'],
    activeTime: 'night',
    aggroRadius: 6,
    respawnTicks: 220,
    isAnimal: false,
    abilities: ['swarm_attack'],
    description: 'Aggressive flying creature that swarms intruders',
  },
  {
    id: 'skeleton',
    name: 'Skeleton',
    tier: 1,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 55,
    baseAttack: 8,
    baseDefense: 5,
    speed: 1,
    stats: { strength: 6, agility: 4, intelligence: 2, perception: 5 },
    loot: [
      { itemType: 'bone', chance: 0.6, quantityMin: 1, quantityMax: 3 },
      { itemType: 'old_weapon', chance: 0.15, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['ruins', 'cemetery'],
    activeTime: 'night',
    aggroRadius: 5,
    respawnTicks: 400,
    isAnimal: false,
    description: 'Animated bones of fallen warriors',
  },
  {
    id: 'zombie',
    name: 'Zombie',
    tier: 1,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 80,
    baseAttack: 6,
    baseDefense: 3,
    speed: 0.5,
    stats: { strength: 7, agility: 2, intelligence: 1, perception: 4 },
    loot: [
      { itemType: 'rotten_flesh', chance: 0.7, quantityMin: 1, quantityMax: 1 },
      { itemType: 'old_armor', chance: 0.05, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['ruins', 'cemetery'],
    activeTime: 'night',
    aggroRadius: 4,
    respawnTicks: 450,
    isAnimal: false,
    description: 'Shambling undead with insatiable hunger',
  },

  // --- TIER 2: INTERMEDIATE MONSTERS ---
  {
    id: 'goblin',
    name: 'Goblin',
    tier: 2,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 45,
    baseAttack: 7,
    baseDefense: 3,
    speed: 1.5,
    stats: { strength: 5, agility: 6, intelligence: 4, perception: 5 },
    loot: [
      { itemType: 'gold_coin', chance: 0.5, quantityMin: 1, quantityMax: 5 },
      { itemType: 'rusty_dagger', chance: 0.15, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['forest', 'cave', 'dense_forest'],
    activeTime: 'any',
    aggroRadius: 5,
    respawnTicks: 400,
    isAnimal: false,
    packType: 'goblin_tribe',
    description: 'Small, cunning humanoid that attacks in groups',
  },
  {
    id: 'goblin_shaman',
    name: 'Goblin Shaman',
    tier: 2,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 35,
    baseAttack: 5,
    baseDefense: 2,
    speed: 1,
    stats: { strength: 3, agility: 5, intelligence: 7, perception: 6 },
    loot: [
      { itemType: 'magic_herb', chance: 0.4, quantityMin: 1, quantityMax: 2 },
      { itemType: 'shaman_staff', chance: 0.1, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['forest', 'cave'],
    activeTime: 'any',
    aggroRadius: 6,
    respawnTicks: 500,
    isAnimal: false,
    abilities: ['heal_allies', 'buff_allies'],
    description: 'Goblin spellcaster that supports its tribe with magic',
  },
  {
    id: 'goblin_chief',
    name: 'Goblin Chief',
    tier: 2,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 80,
    baseAttack: 12,
    baseDefense: 6,
    speed: 1.5,
    stats: { strength: 8, agility: 6, intelligence: 6, perception: 7 },
    loot: [
      { itemType: 'chief_medallion', chance: 0.3, quantityMin: 1, quantityMax: 1 },
      { itemType: 'gold_coin', chance: 0.8, quantityMin: 5, quantityMax: 15 },
    ],
    habitat: ['forest', 'cave'],
    activeTime: 'any',
    aggroRadius: 7,
    respawnTicks: 800,
    isAnimal: false,
    abilities: ['rally_cry', 'command_troops'],
    description: 'Leader of a goblin tribe, feared by its underlings',
  },
  {
    id: 'orc_warrior',
    name: 'Orc Warrior',
    tier: 2,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 90,
    baseAttack: 14,
    baseDefense: 8,
    speed: 1,
    stats: { strength: 12, agility: 4, intelligence: 3, perception: 5 },
    loot: [
      { itemType: 'orc_weapon', chance: 0.3, quantityMin: 1, quantityMax: 1 },
      { itemType: 'iron_ingot', chance: 0.4, quantityMin: 1, quantityMax: 2 },
    ],
    habitat: ['mountain', 'desert'],
    activeTime: 'any',
    aggroRadius: 6,
    respawnTicks: 600,
    isAnimal: false,
    description: 'Brutish humanoid warrior with crude but effective weapons',
  },
  {
    id: 'orc_berserker',
    name: 'Orc Berserker',
    tier: 2,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 80,
    baseAttack: 20,
    baseDefense: 4,
    speed: 1.5,
    stats: { strength: 16, agility: 6, intelligence: 2, perception: 4 },
    loot: [
      { itemType: 'orc_weapon', chance: 0.4, quantityMin: 1, quantityMax: 1 },
      { itemType: 'blood_stone', chance: 0.1, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['mountain', 'desert'],
    activeTime: 'any',
    aggroRadius: 8,
    respawnTicks: 700,
    isAnimal: false,
    abilities: ['berserk_rage'],
    description: 'Fearsome orc warrior that enters unstoppable rage',
  },
  {
    id: 'bandit',
    name: 'Bandit',
    tier: 2,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 70,
    baseAttack: 11,
    baseDefense: 6,
    speed: 1.5,
    stats: { strength: 7, agility: 8, intelligence: 5, perception: 6 },
    loot: [
      { itemType: 'gold_coin', chance: 0.8, quantityMin: 3, quantityMax: 10 },
      { itemType: 'stolen_goods', chance: 0.3, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['road', 'forest'],
    activeTime: 'any',
    aggroRadius: 7,
    respawnTicks: 500,
    isAnimal: false,
    packType: 'bandit_gang',
    description: 'Outlaw that preys on travelers',
  },
  {
    id: 'bandit_leader',
    name: 'Bandit Leader',
    tier: 2,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 100,
    baseAttack: 15,
    baseDefense: 8,
    speed: 1.5,
    stats: { strength: 9, agility: 9, intelligence: 7, perception: 8 },
    loot: [
      { itemType: 'treasure_map', chance: 0.2, quantityMin: 1, quantityMax: 1 },
      { itemType: 'gold_coin', chance: 0.9, quantityMin: 10, quantityMax: 25 },
    ],
    habitat: ['forest', 'cave'],
    activeTime: 'any',
    aggroRadius: 8,
    respawnTicks: 900,
    isAnimal: false,
    description: 'Cunning leader of a bandit gang',
  },
  {
    id: 'harpy',
    name: 'Harpy',
    tier: 2,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 50,
    baseAttack: 10,
    baseDefense: 3,
    speed: 2.5,
    stats: { strength: 6, agility: 10, intelligence: 5, perception: 8 },
    loot: [{ itemType: 'harpy_feather', chance: 0.5, quantityMin: 2, quantityMax: 2 }],
    habitat: ['mountain', 'cliff'],
    activeTime: 'any',
    aggroRadius: 7,
    respawnTicks: 550,
    isAnimal: false,
    abilities: ['flying', 'sonic_scream'],
    description: 'Winged monster with woman\'s face and bird\'s body',
  },
  {
    id: 'troll',
    name: 'Troll',
    tier: 2,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 120,
    baseAttack: 14,
    baseDefense: 8,
    speed: 0.5,
    stats: { strength: 14, agility: 3, intelligence: 2, perception: 4 },
    loot: [
      { itemType: 'troll_hide', chance: 0.4, quantityMin: 1, quantityMax: 1 },
      { itemType: 'club', chance: 0.2, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['cave', 'bridge', 'dense_forest'],
    activeTime: 'any',
    aggroRadius: 6,
    respawnTicks: 800,
    isAnimal: false,
    abilities: ['regeneration'],
    weaknesses: ['fire'],
    description: 'Large regenerating monster, vulnerable to fire',
  },
  {
    id: 'ghost',
    name: 'Ghost',
    tier: 2,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 60,
    baseAttack: 12,
    baseDefense: 10,
    speed: 1,
    stats: { strength: 4, agility: 6, intelligence: 8, perception: 9 },
    loot: [{ itemType: 'ectoplasm', chance: 0.4, quantityMin: 1, quantityMax: 1 }],
    habitat: ['ruins', 'cemetery'],
    activeTime: 'night',
    aggroRadius: 5,
    respawnTicks: 600,
    isAnimal: false,
    immunities: ['physical'],
    weaknesses: ['magic'],
    description: 'Ethereal spirit immune to physical attacks',
  },
  {
    id: 'wraith',
    name: 'Wraith',
    tier: 2,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 80,
    baseAttack: 16,
    baseDefense: 12,
    speed: 1.5,
    stats: { strength: 5, agility: 7, intelligence: 10, perception: 10 },
    loot: [{ itemType: 'shadow_essence', chance: 0.3, quantityMin: 1, quantityMax: 1 }],
    habitat: ['ruins', 'cemetery'],
    activeTime: 'night',
    aggroRadius: 6,
    respawnTicks: 700,
    isAnimal: false,
    abilities: ['life_drain'],
    immunities: ['physical'],
    description: 'Powerful undead that drains life force',
  },

  // --- TIER 3: ADVANCED MONSTERS ---
  {
    id: 'ogre',
    name: 'Ogre',
    tier: 3,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 200,
    baseAttack: 20,
    baseDefense: 10,
    speed: 0.5,
    stats: { strength: 18, agility: 3, intelligence: 2, perception: 4 },
    loot: [
      { itemType: 'ogre_bone', chance: 0.5, quantityMin: 2, quantityMax: 2 },
      { itemType: 'gold_coin', chance: 0.6, quantityMin: 5, quantityMax: 15 },
    ],
    habitat: ['mountain', 'cave'],
    activeTime: 'any',
    aggroRadius: 7,
    respawnTicks: 1000,
    isAnimal: false,
    description: 'Massive brute with incredible strength',
  },
  {
    id: 'wyvern',
    name: 'Wyvern',
    tier: 3,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 150,
    baseAttack: 18,
    baseDefense: 12,
    speed: 2.5,
    stats: { strength: 12, agility: 10, intelligence: 5, perception: 9 },
    loot: [
      { itemType: 'wyvern_scale', chance: 0.4, quantityMin: 2, quantityMax: 2 },
      { itemType: 'wyvern_venom', chance: 0.3, quantityMin: 1, quantityMax: 1 },
    ],
    habitat: ['mountain'],
    activeTime: 'any',
    aggroRadius: 9,
    respawnTicks: 1200,
    isAnimal: false,
    abilities: ['flying', 'poison_breath'],
    description: 'Lesser dragon with venomous breath',
  },
  {
    id: 'basilisk',
    name: 'Basilisk',
    tier: 3,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 130,
    baseAttack: 15,
    baseDefense: 15,
    speed: 0.5,
    stats: { strength: 10, agility: 4, intelligence: 6, perception: 10 },
    loot: [{ itemType: 'petrified_eye', chance: 0.2, quantityMin: 1, quantityMax: 1 }],
    habitat: ['cave'],
    activeTime: 'any',
    aggroRadius: 8,
    respawnTicks: 1100,
    isAnimal: false,
    abilities: ['petrifying_gaze'],
    description: 'Serpentine monster whose gaze turns victims to stone',
  },
  {
    id: 'minotaur',
    name: 'Minotaur',
    tier: 3,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 180,
    baseAttack: 22,
    baseDefense: 12,
    speed: 1.5,
    stats: { strength: 16, agility: 6, intelligence: 4, perception: 6 },
    loot: [{ itemType: 'minotaur_horn', chance: 0.3, quantityMin: 1, quantityMax: 1 }],
    habitat: ['ruins', 'cave'],
    activeTime: 'any',
    aggroRadius: 8,
    respawnTicks: 1200,
    isAnimal: false,
    abilities: ['charge_attack'],
    description: 'Bull-headed warrior that charges with devastating force',
  },
  {
    id: 'lich',
    name: 'Lich',
    tier: 3,
    creatureType: 'monster',
    behavior: 'boss',
    baseHp: 160,
    baseAttack: 25,
    baseDefense: 8,
    speed: 1,
    stats: { strength: 6, agility: 5, intelligence: 18, perception: 12 },
    loot: [
      { itemType: 'lich_phylactery', chance: 0.15, quantityMin: 1, quantityMax: 1 },
      { itemType: 'shadow_essence', chance: 0.5, quantityMin: 3, quantityMax: 3 },
    ],
    habitat: ['ruins'],
    activeTime: 'any',
    aggroRadius: 10,
    respawnTicks: 2000,
    isAnimal: false,
    abilities: ['summon_undead', 'dark_magic'],
    immunities: ['poison'],
    description: 'Undead sorcerer of immense power',
  },

  // --- TIER 4: BOSS MONSTERS ---
  {
    id: 'dragon_whelp',
    name: 'Dragon Whelp',
    tier: 4,
    creatureType: 'monster',
    behavior: 'aggressive',
    baseHp: 200,
    baseAttack: 20,
    baseDefense: 15,
    speed: 2,
    stats: { strength: 14, agility: 8, intelligence: 8, perception: 10 },
    loot: [{ itemType: 'dragon_scale', chance: 0.5, quantityMin: 2, quantityMax: 2 }],
    habitat: ['mountain', 'volcano'],
    activeTime: 'any',
    aggroRadius: 9,
    respawnTicks: 1500,
    isAnimal: false,
    abilities: ['fire_breath_weak', 'flying'],
    description: 'Young dragon, deadly but not yet fully grown',
  },
  {
    id: 'dragon',
    name: 'Dragon',
    tier: 4,
    creatureType: 'monster',
    behavior: 'boss',
    baseHp: 1000,
    baseAttack: 50,
    baseDefense: 30,
    speed: 2,
    stats: { strength: 25, agility: 12, intelligence: 15, perception: 18 },
    loot: [
      { itemType: 'dragon_scale', chance: 0.8, quantityMin: 10, quantityMax: 10 },
      { itemType: 'dragon_heart', chance: 0.3, quantityMin: 1, quantityMax: 1 },
      { itemType: 'gold_coin', chance: 1.0, quantityMin: 50, quantityMax: 200 },
    ],
    habitat: ['volcano', 'mountain'],
    activeTime: 'any',
    aggroRadius: 15,
    respawnTicks: 5000,
    isAnimal: false,
    abilities: ['fire_breath', 'flying', 'tail_sweep'],
    denType: 'dragon_lair',
    description: 'Ancient wyrm of legendary power, guardian of vast treasure',
  },
  {
    id: 'ancient_golem',
    name: 'Ancient Golem',
    tier: 4,
    creatureType: 'monster',
    behavior: 'boss',
    baseHp: 800,
    baseAttack: 35,
    baseDefense: 40,
    speed: 0.5,
    stats: { strength: 20, agility: 2, intelligence: 1, perception: 8 },
    loot: [{ itemType: 'golem_core', chance: 0.3, quantityMin: 1, quantityMax: 1 }],
    habitat: ['ruins'],
    activeTime: 'any',
    aggroRadius: 10,
    respawnTicks: 4000,
    isAnimal: false,
    immunities: ['magic'],
    weaknesses: ['physical'],
    denType: 'ancient_ruins_dungeon',
    description: 'Colossal construct powered by ancient magic',
  },

  // --- TIER 5: WORLD BOSSES (EVENT-ONLY) ---
  {
    id: 'world_serpent',
    name: 'World Serpent',
    tier: 5,
    creatureType: 'monster',
    behavior: 'boss',
    baseHp: 3000,
    baseAttack: 60,
    baseDefense: 35,
    speed: 1,
    stats: { strength: 30, agility: 10, intelligence: 12, perception: 15 },
    loot: [{ itemType: 'leviathan_scale', chance: 0.5, quantityMin: 1, quantityMax: 1 }],
    habitat: ['ocean'],
    activeTime: 'any',
    aggroRadius: 20,
    respawnTicks: 10000,
    isAnimal: false,
    abilities: ['tidal_wave', 'constrict'],
    description: 'Legendary sea serpent of apocalyptic proportions',
  },
  {
    id: 'demon_lord',
    name: 'Demon Lord',
    tier: 5,
    creatureType: 'monster',
    behavior: 'boss',
    baseHp: 2500,
    baseAttack: 55,
    baseDefense: 30,
    speed: 1.5,
    stats: { strength: 22, agility: 15, intelligence: 20, perception: 18 },
    loot: [{ itemType: 'demon_essence', chance: 0.5, quantityMin: 1, quantityMax: 1 }],
    habitat: ['portal'],
    activeTime: 'any',
    aggroRadius: 20,
    respawnTicks: 10000,
    isAnimal: false,
    abilities: ['hellfire', 'summon_demons', 'dark_pact'],
    description: 'Infernal entity from beyond the mortal realm',
  },
]

// ============================================================================
// COMBINED CREATURE TEMPLATES
// ============================================================================

export const CREATURE_TEMPLATES: CreatureTemplate[] = [
  ...ANIMAL_TEMPLATES,
  ...MONSTER_TEMPLATES,
]

// ============================================================================
// BIOME SPAWN TABLES
// ============================================================================

export const BIOME_SPAWN_TABLE: Record<
  string,
  { templateId: string; weight: number; timeRestriction?: 'day' | 'night' }[]
> = {
  grass: [
    { templateId: 'rabbit', weight: 30 },
    { templateId: 'deer', weight: 15 },
    { templateId: 'butterfly', weight: 20 },
    { templateId: 'boar', weight: 8 },
    { templateId: 'slime', weight: 5 },
    { templateId: 'horse', weight: 5 },
  ],
  meadow: [
    { templateId: 'rabbit', weight: 25 },
    { templateId: 'deer', weight: 20 },
    { templateId: 'butterfly', weight: 15 },
    { templateId: 'sheep', weight: 10 },
    { templateId: 'horse', weight: 8 },
  ],
  forest: [
    { templateId: 'deer', weight: 15 },
    { templateId: 'wolf', weight: 12 },
    { templateId: 'boar', weight: 10 },
    { templateId: 'bear', weight: 5 },
    { templateId: 'goblin', weight: 12 },
    { templateId: 'giant_spider', weight: 5 },
    { templateId: 'bandit', weight: 8 },
  ],
  dense_forest: [
    { templateId: 'wolf', weight: 15 },
    { templateId: 'dire_wolf', weight: 5 },
    { templateId: 'giant_spider', weight: 12 },
    { templateId: 'troll', weight: 8 },
    { templateId: 'goblin', weight: 10 },
  ],
  mountain: [
    { templateId: 'eagle', weight: 15 },
    { templateId: 'orc_warrior', weight: 12 },
    { templateId: 'wyvern', weight: 3 },
    { templateId: 'griffin', weight: 2 },
    { templateId: 'bat', weight: 8 },
    { templateId: 'ogre', weight: 5 },
  ],
  desert: [
    { templateId: 'basilisk', weight: 8 },
    { templateId: 'bandit', weight: 15 },
    { templateId: 'skeleton', weight: 10, timeRestriction: 'night' },
  ],
  swamp: [
    { templateId: 'slime', weight: 20 },
    { templateId: 'zombie', weight: 12, timeRestriction: 'night' },
    { templateId: 'ghost', weight: 8, timeRestriction: 'night' },
    { templateId: 'giant_spider', weight: 10 },
  ],
  snow: [
    { templateId: 'dire_wolf', weight: 15 },
    { templateId: 'wolf', weight: 10 },
    { templateId: 'bear', weight: 8 },
  ],
  cave: [
    { templateId: 'bat', weight: 20 },
    { templateId: 'rat', weight: 18 },
    { templateId: 'skeleton', weight: 12 },
    { templateId: 'giant_spider', weight: 10 },
    { templateId: 'troll', weight: 5 },
  ],
  ruins: [
    { templateId: 'skeleton', weight: 20 },
    { templateId: 'zombie', weight: 15, timeRestriction: 'night' },
    { templateId: 'ghost', weight: 10, timeRestriction: 'night' },
    { templateId: 'wraith', weight: 5, timeRestriction: 'night' },
  ],
  cemetery: [
    { templateId: 'skeleton', weight: 20, timeRestriction: 'night' },
    { templateId: 'zombie', weight: 15, timeRestriction: 'night' },
    { templateId: 'ghost', weight: 12, timeRestriction: 'night' },
    { templateId: 'wraith', weight: 5, timeRestriction: 'night' },
  ],
  farmland: [
    { templateId: 'chicken', weight: 25 },
    { templateId: 'cow', weight: 15 },
    { templateId: 'sheep', weight: 15 },
    { templateId: 'rabbit', weight: 10 },
  ],
  water: [{ templateId: 'fish', weight: 40 }],
  river: [{ templateId: 'fish', weight: 30 }],
}

// ============================================================================
// DEN TEMPLATES
// ============================================================================

export const DEN_TEMPLATES: Record<DenType, DenTemplate> = {
  goblin_camp: {
    denType: 'goblin_camp',
    name: 'Goblin Camp',
    tier: 2,
    creatureTemplates: [
      { templateId: 'goblin', count: [10, 20] },
      { templateId: 'goblin_shaman', count: [1, 2] },
    ],
    bossTemplateId: 'goblin_chief',
    floors: 1,
    roomsPerFloor: [3, 5],
    respawnTicks: 500,
    description: 'A crude camp of goblins with wooden fences and tattered tents',
  },
  wolf_den: {
    denType: 'wolf_den',
    name: 'Wolf Den',
    tier: 2,
    creatureTemplates: [{ templateId: 'wolf', count: [5, 8] }],
    bossTemplateId: 'dire_wolf',
    floors: 1,
    roomsPerFloor: [2, 3],
    respawnTicks: 400,
    description: 'A cave entrance littered with bones — home to a wolf pack',
  },
  bandit_hideout: {
    denType: 'bandit_hideout',
    name: 'Bandit Hideout',
    tier: 2,
    creatureTemplates: [{ templateId: 'bandit', count: [8, 15] }],
    bossTemplateId: 'bandit_leader',
    floors: 1,
    roomsPerFloor: [3, 5],
    respawnTicks: 600,
    description: 'A hidden camp where bandits store stolen goods',
  },
  spider_nest: {
    denType: 'spider_nest',
    name: 'Spider Nest',
    tier: 2,
    creatureTemplates: [{ templateId: 'giant_spider', count: [10, 15] }],
    bossTemplateId: 'giant_spider',
    floors: 2,
    roomsPerFloor: [3, 5],
    respawnTicks: 450,
    description: 'Thick webs cover every surface of this dark cavern',
  },
  orc_fortress: {
    denType: 'orc_fortress',
    name: 'Orc Fortress',
    tier: 3,
    creatureTemplates: [
      { templateId: 'orc_warrior', count: [15, 25] },
      { templateId: 'orc_berserker', count: [3, 5] },
    ],
    bossTemplateId: 'orc_berserker',
    floors: 2,
    roomsPerFloor: [4, 6],
    respawnTicks: 800,
    description: 'A fortified mountain stronghold of orc warriors',
  },
  undead_crypt: {
    denType: 'undead_crypt',
    name: 'Undead Crypt',
    tier: 3,
    creatureTemplates: [
      { templateId: 'skeleton', count: [10, 20] },
      { templateId: 'zombie', count: [5, 10] },
      { templateId: 'ghost', count: [3, 5] },
    ],
    bossTemplateId: 'lich',
    floors: 4,
    roomsPerFloor: [3, 5],
    respawnTicks: 1000,
    description: 'Ancient catacombs where the dead refuse to rest',
  },
  dragon_lair: {
    denType: 'dragon_lair',
    name: 'Dragon Lair',
    tier: 4,
    creatureTemplates: [{ templateId: 'dragon_whelp', count: [1, 2] }],
    bossTemplateId: 'dragon',
    floors: 1,
    roomsPerFloor: [2, 3],
    respawnTicks: 2000,
    description: 'The volcanic cave of an ancient dragon, filled with treasure',
  },
  ancient_ruins_dungeon: {
    denType: 'ancient_ruins_dungeon',
    name: 'Ancient Ruins',
    tier: 4,
    creatureTemplates: [
      { templateId: 'skeleton', count: [10, 15] },
      { templateId: 'minotaur', count: [2, 3] },
    ],
    bossTemplateId: 'ancient_golem',
    floors: 4,
    roomsPerFloor: [4, 6],
    respawnTicks: 1500,
    description: 'Crumbling ruins hiding ancient golems and forgotten treasures',
  },
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Get creature template by ID
 */
export function getCreatureTemplate(id: string): CreatureTemplate | undefined {
  return CREATURE_TEMPLATES.find((t) => t.id === id)
}

/**
 * Get spawnable creatures for a biome, filtered by time of day
 */
export function getSpawnableCreatures(
  biome: string,
  isNight: boolean
): { templateId: string; weight: number }[] {
  const entries = BIOME_SPAWN_TABLE[biome] ?? []
  return entries.filter((e) => {
    if (e.timeRestriction === 'night' && !isNight) return false
    if (e.timeRestriction === 'day' && isNight) return false
    return true
  })
}
